project_id = "unwxkufzauulzhmjxxqi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[db]
port = 54322

[edge_functions]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.cancel-test-subscription]
verify_jwt = false

[functions.reactivate-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.handle-stripe-webhook]
verify_jwt = false