-- MEGA TRADUZIONE DI TUTTI GLI ESERCIZI DAL ITALIANO ALL'INGLESE
-- Aggiorna TUTTI i titoli degli esercizi

UPDATE ai_training_exercises SET title = 'Morning Positive Routine' WHERE title = '🌅 Routine Positiva Nuova';
UPDATE ai_training_exercises SET title = 'Stimulating Colors Game' WHERE title = '🌈 Gioco Colori Stimolanti';
UPDATE ai_training_exercises SET title = 'Simple Wavy Path' WHERE title = '🌊 Percorso Ondulato Semplice';
UPDATE ai_training_exercises SET title = 'Gentle Olfactory Awakening' WHERE title = '🌸 Risveglio Olfattivo Delicato';
UPDATE ai_training_exercises SET title = 'Guided Indoor Exploration' WHERE title = '🌿 Esplorazione Guidata Indoor';
UPDATE ai_training_exercises SET title = 'Motivating Surprise Box' WHERE title = '🎁 Scatola Sorpresa Motivante';
UPDATE ai_training_exercises SET title = 'Progress Celebration' WHERE title = '🎊 Celebrazione Progressi';
UPDATE ai_training_exercises SET title = 'Free Creative Activity' WHERE title = '🎨 Attività Creativa Libera';
UPDATE ai_training_exercises SET title = 'Motivating Interactive Game' WHERE title = '🎪 Gioco Interattivo Motivante';
UPDATE ai_training_exercises SET title = 'Easy Motivating Tricks' WHERE title = '🎪 Trick Facili Motivanti';
UPDATE ai_training_exercises SET title = 'Basic Target Training' WHERE title = '🎯 Target Training Base';
UPDATE ai_training_exercises SET title = 'Multiple Choice Game' WHERE title = '🎲 Gioco delle Scelte Multiple';
UPDATE ai_training_exercises SET title = 'Gentle Sound Awakening' WHERE title = '🎵 Risveglio Sonoro Dolce';
UPDATE ai_training_exercises SET title = 'Gentle Ball Game' WHERE title = '🎾 Gioco Palla Dolce';
UPDATE ai_training_exercises SET title = 'Controlled Gentle Socialization' WHERE title = '👥 Socializzazione Dolce Controllata';
UPDATE ai_training_exercises SET title = 'Motivating Relaxing Massage' WHERE title = '💆 Massaggio Rilassante Motivante';
UPDATE ai_training_exercises SET title = 'Positive Future Planning' WHERE title = '💫 Pianificazione Futuro Positivo';
UPDATE ai_training_exercises SET title = 'Simple Motivating Sequences' WHERE title = '🔄 Sequenze Semplici Motivanti';
UPDATE ai_training_exercises SET title = 'Guided Olfactory Search' WHERE title = '🔍 Ricerca Olfattiva Guidata';
UPDATE ai_training_exercises SET title = 'Simple Hidden Treasure' WHERE title = '🤲 Tesoro Nascosto Semplice';
UPDATE ai_training_exercises SET title = 'Easy Food Puzzle' WHERE title = '🧩 Puzzle Alimentare Facile';
UPDATE ai_training_exercises SET title = 'Soft Texture Exploration' WHERE title = '🪶 Esplorazione Texture Morbide';
UPDATE ai_training_exercises SET title = 'Motivated Autonomy Test' WHERE title = '🚀 Test Autonomia Motivata';
UPDATE ai_training_exercises SET title = 'Awakening Steps' WHERE title = '🚶 Passi di Risveglio';

-- Continua con gli altri titoli...
UPDATE ai_training_exercises SET title = 'Multi-Pet Controlled Feeding' WHERE title = 'Alimentazione Controllata Multi-Pet';
UPDATE ai_training_exercises SET title = 'Timed Fractioned Feeding' WHERE title = 'Alimentazione Frazionata Temporizzata';
UPDATE ai_training_exercises SET title = 'Alternative Response Training' WHERE title = 'Alternative Response Training';
UPDATE ai_training_exercises SET title = 'Positive Anticipation' WHERE title = 'Anticipazione Positiva';
UPDATE ai_training_exercises SET title = 'Aromatherapy Evening Calm' WHERE title = 'Aromatherapy Evening Calm';
UPDATE ai_training_exercises SET title = 'Complex Positive Associations' WHERE title = 'Associazioni Positive Complesse';
UPDATE ai_training_exercises SET title = 'Shared Attention with Owner' WHERE title = 'Attenzione Condivisa con il Proprietario';
UPDATE ai_training_exercises SET title = 'Home Audit and Risk Zone Identification' WHERE title = 'Audit Casa e Identificazione Zone Rischio';
UPDATE ai_training_exercises SET title = 'Self-Control with Frustration' WHERE title = 'Autocontrollo con Frustrazione';
UPDATE ai_training_exercises SET title = 'Self-Control During Exposure' WHERE title = 'Autocontrollo Durante Esposizione';
UPDATE ai_training_exercises SET title = 'Multi-Distraction Self-Control' WHERE title = 'Autocontrollo Multi-Distrazione';
UPDATE ai_training_exercises SET title = 'Real Situations Self-Control' WHERE title = 'Autocontrollo Situazioni Reali';
UPDATE ai_training_exercises SET title = 'Gradual Approach to Resources' WHERE title = 'Avvicinamento Graduale alle Risorse';
UPDATE ai_training_exercises SET title = 'Behavioral Baseline' WHERE title = 'Baseline Comportamentale';
UPDATE ai_training_exercises SET title = 'Baseline Impulse Control' WHERE title = 'Baseline Impulse Control';
UPDATE ai_training_exercises SET title = 'Breathing Harmony Technique' WHERE title = 'Breathing Harmony Technique';
UPDATE ai_training_exercises SET title = 'Multi-Level Treasure Hunt' WHERE title = 'Caccia al Tesoro Multi-Livello';
UPDATE ai_training_exercises SET title = 'Speed Control Walking' WHERE title = 'Camminata Controllo Velocità';
UPDATE ai_training_exercises SET title = 'Celebration and Success Consolidation' WHERE title = 'Celebration e Consolidamento Successi';
UPDATE ai_training_exercises SET title = 'Celebration and Graduation' WHERE title = 'Celebrazione e Graduation';
UPDATE ai_training_exercises SET title = 'Celebration and Final Reinforcement' WHERE title = 'Celebrazione e Rinforzo Finale';
UPDATE ai_training_exercises SET title = 'Advanced Impulse Challenge' WHERE title = 'Challenge Impulsi Avanzato';
UPDATE ai_training_exercises SET title = 'Choice-Based Exposure' WHERE title = 'Choice-Based Exposure';
UPDATE ai_training_exercises SET title = 'Circadian Light Therapy' WHERE title = 'Circadian Light Therapy';
UPDATE ai_training_exercises SET title = 'Basic Home Agility Circuit' WHERE title = 'Circuito Agility Casa Base';
UPDATE ai_training_exercises SET title = 'Cognitive Load Training' WHERE title = 'Cognitive Load Training';
UPDATE ai_training_exercises SET title = 'Advanced "Drop It" Command' WHERE title = 'Comando "Drop It" Avanzato';
UPDATE ai_training_exercises SET title = 'Basic "LEAVE" Command' WHERE title = 'Comando "LASCIA" Base';
UPDATE ai_training_exercises SET title = 'Everyone to Their Place Command' WHERE title = 'Comando "Ognuno al Suo Posto"';
UPDATE ai_training_exercises SET title = 'Progressive Wait Command' WHERE title = 'Comando Aspetta Progressivo';
UPDATE ai_training_exercises SET title = 'Graduated Audio-Visual Combination' WHERE title = 'Combinazione Audio-Visiva Graduata';
UPDATE ai_training_exercises SET title = 'Comfort Zone Optimization' WHERE title = 'Comfort Zone Optimization';
UPDATE ai_training_exercises SET title = 'Multiple Bowl Sharing' WHERE title = 'Condivisione Ciotole Multiple';
UPDATE ai_training_exercises SET title = 'Guided Sharing with Owner' WHERE title = 'Condivisione Guidata con Proprietario';
UPDATE ai_training_exercises SET title = 'Space Sharing with Other Animals' WHERE title = 'Condivisione Spazio con Altri Animali';
UPDATE ai_training_exercises SET title = 'Calm Marker Conditioning' WHERE title = 'Condizionamento Marker di Calma';
UPDATE ai_training_exercises SET title = 'Emotional Consolidation' WHERE title = 'Consolidamento Emotivo';
UPDATE ai_training_exercises SET title = 'Final Consolidation and Evaluation' WHERE title = 'Consolidamento Finale e Valutazione';
UPDATE ai_training_exercises SET title = 'Learned Strategies Consolidation' WHERE title = 'Consolidamento Strategie Apprese';
UPDATE ai_training_exercises SET title = 'Intensive Eye Contact' WHERE title = 'Contatto Visivo Intensivo';
UPDATE ai_training_exercises SET title = 'Social Excitement Control' WHERE title = 'Controllo Eccitazione Sociale';
UPDATE ai_training_exercises SET title = 'Door Impulse Control' WHERE title = 'Controllo Impulsi Porta';
UPDATE ai_training_exercises SET title = 'Impulse Control Near Resources' WHERE title = 'Controllo Impulsi Vicino a Risorse';
UPDATE ai_training_exercises SET title = 'Maximum Distance Counter-Conditioning' WHERE title = 'Counter-Conditioning Distanza Massima';
UPDATE ai_training_exercises SET title = 'Counter-Conditioning Level 1' WHERE title = 'Counter-Conditioning Livello 1';
UPDATE ai_training_exercises SET title = 'Personal Chewing Corner Creation' WHERE title = 'Creazione Angolo Masticazione Personale';
UPDATE ai_training_exercises SET title = 'Safe Space Creation' WHERE title = 'Creazione Safe Space';
UPDATE ai_training_exercises SET title = 'Personalized Safe Space Creation' WHERE title = 'Creazione Safe Space Personalizzato';
UPDATE ai_training_exercises SET title = 'Deep Sleep Induction' WHERE title = 'Deep Sleep Induction';
UPDATE ai_training_exercises SET title = 'Advanced Cue Desensitization' WHERE title = 'Desensibilizzazione Avanzata Cue';
UPDATE ai_training_exercises SET title = 'Gradual Approach Desensitization' WHERE title = 'Desensibilizzazione Avvicinamento Graduale';
UPDATE ai_training_exercises SET title = 'Hands Near Food Desensitization' WHERE title = 'Desensibilizzazione Mani Vicino al Cibo';
UPDATE ai_training_exercises SET title = 'Human Presence Desensitization' WHERE title = 'Desensibilizzazione Presenza Umana';
UPDATE ai_training_exercises SET title = 'Visual Distance Desensitization' WHERE title = 'Desensibilizzazione Visiva Distanza';
UPDATE ai_training_exercises SET title = 'Advanced Discrimination' WHERE title = 'Discriminazione Avanzata';
UPDATE ai_training_exercises SET title = 'Distance Management Training' WHERE title = 'Distance Management Training';
UPDATE ai_training_exercises SET title = 'Progressive Exposure Duration' WHERE title = 'Durata Esposizione Progressiva';
UPDATE ai_training_exercises SET title = 'Food Anxiety Elimination' WHERE title = 'Eliminazione Ansia Alimentare';
UPDATE ai_training_exercises SET title = 'Food Competition Elimination' WHERE title = 'Eliminazione Competizione Alimentare';
UPDATE ai_training_exercises SET title = 'Emergency Redirect Training' WHERE title = 'Emergency Redirect Training';
UPDATE ai_training_exercises SET title = 'Energy Balance Training' WHERE title = 'Energy Balance Training';
UPDATE ai_training_exercises SET title = 'Wait Your Turn Exercise' WHERE title = 'Esercizio "Aspetta il Tuo Turno"';
UPDATE ai_training_exercises SET title = '2-Minute Extension' WHERE title = 'Estensione a 2 Minuti';
UPDATE ai_training_exercises SET title = 'Focus in Movement' WHERE title = 'Focus in Movimento';
UPDATE ai_training_exercises SET title = 'Controlled Free Choice Feeding' WHERE title = 'Free Choice Feeding Controllato';
UPDATE ai_training_exercises SET title = 'Free Choice Social Interaction' WHERE title = 'Free Choice Social Interaction';
UPDATE ai_training_exercises SET title = 'Cooperative "Tug of War" Game' WHERE title = 'Gioco Cooperativo "Tira e Molla"';
UPDATE ai_training_exercises SET title = 'Complex Cooperative Game' WHERE title = 'Gioco Cooperativo Complesso';
UPDATE ai_training_exercises SET title = 'Extended Interactive Play' WHERE title = 'Gioco Interattivo Prolungato';
UPDATE ai_training_exercises SET title = 'Parallel Play with Other Animals' WHERE title = 'Gioco Parallelo con Altri Animali';
UPDATE ai_training_exercises SET title = 'Pause and Go Game' WHERE title = 'Gioco Pausa e Vai';
UPDATE ai_training_exercises SET title = 'Sudden Stop Game' WHERE title = 'Gioco Stop Improvviso';
UPDATE ai_training_exercises SET title = 'Structured Anti-Boredom Play' WHERE title = 'Gioco Strutturato Anti-Noia';
UPDATE ai_training_exercises SET title = 'Supervised Group Activity' WHERE title = 'Group Activity Supervisionata';
UPDATE ai_training_exercises SET title = 'Controlled Hand Feeding' WHERE title = 'Hand Feeding Controllato';

-- Continua con Safety Threshold Identification che è già tradotto
UPDATE ai_training_exercises SET title = 'Primary Trigger Identification' WHERE title = 'Identificazione Trigger Primario';
UPDATE ai_training_exercises SET title = 'Impulse Control with Food' WHERE title = 'Impulse Control con Cibo';
UPDATE ai_training_exercises SET title = 'Graduated Impulse Control' WHERE title = 'Impulse Control Graduato';
UPDATE ai_training_exercises SET title = 'Independent Sleep Mastery' WHERE title = 'Independent Sleep Mastery';
UPDATE ai_training_exercises SET title = 'Alternative Behaviors Integration' WHERE title = 'Integration Alternative Behaviors';
UPDATE ai_training_exercises SET title = 'Social Integration Test' WHERE title = 'Integration Test Sociale';
UPDATE ai_training_exercises SET title = 'Comfort Object Introduction' WHERE title = 'Introduzione Comfort Object';
UPDATE ai_training_exercises SET title = 'Gradual Second Animal Introduction' WHERE title = 'Introduzione Graduale Secondo Animale';
UPDATE ai_training_exercises SET title = 'Human Presence Introduction at Distance' WHERE title = 'Introduzione Presenza Umana a Distanza';
UPDATE ai_training_exercises SET title = 'Voice Recording Introduction' WHERE title = 'Introduzione Registrazione Voce';
UPDATE ai_training_exercises SET title = 'Slow Feeding Introduction' WHERE title = 'Introduzione Slow Feeding';
UPDATE ai_training_exercises SET title = 'Snuffle Mat Introduction' WHERE title = 'Introduzione Tappetino Snuffle';
UPDATE ai_training_exercises SET title = 'Leadership and Initiative' WHERE title = 'Leadership e Iniziativa';
UPDATE ai_training_exercises SET title = 'Long-term Sleep Success Plan' WHERE title = 'Long-term Sleep Success Plan';
UPDATE ai_training_exercises SET title = 'Maintenance Protocol Setup' WHERE title = 'Maintenance Protocol Setup';
UPDATE ai_training_exercises SET title = 'Evening Anti-Stress Massage' WHERE title = 'Massaggio Serale Anti-Stress';
UPDATE ai_training_exercises SET title = 'Master Sleep Routine Integration' WHERE title = 'Master Sleep Routine Integration';
UPDATE ai_training_exercises SET title = 'Mastery Demonstration' WHERE title = 'Mastery Demonstration';
UPDATE ai_training_exercises SET title = 'Meditation Walking' WHERE title = 'Meditation Walking';
UPDATE ai_training_exercises SET title = 'Guided Pet Meditation' WHERE title = 'Meditazione Guidata Pet';
UPDATE ai_training_exercises SET title = 'Controlled Meet-and-Greet' WHERE title = 'Meet-and-Greet Controllato';
UPDATE ai_training_exercises SET title = 'Intensive Mental Stimulation' WHERE title = 'Mental Stimulation Intensiva';
UPDATE ai_training_exercises SET title = 'Audio Micro-Exposure' WHERE title = 'Micro-Esposizione Audio';
UPDATE ai_training_exercises SET title = '30-Second Micro-Exits' WHERE title = 'Micro-Uscite di 30 Secondi';
UPDATE ai_training_exercises SET title = 'Multi-Bowl Challenge' WHERE title = 'Multi-Bowl Challenge';
UPDATE ai_training_exercises SET title = 'Natural Rhythm Reinforcement' WHERE title = 'Natural Rhythm Reinforcement';
UPDATE ai_training_exercises SET title = 'Return Neutralization' WHERE title = 'Neutralizzazione Rientro';
UPDATE ai_training_exercises SET title = 'Night Distraction Management' WHERE title = 'Night Distraction Management';
UPDATE ai_training_exercises SET title = 'Night Security Routine' WHERE title = 'Night Security Routine';
UPDATE ai_training_exercises SET title = 'Passive Environment Observation' WHERE title = 'Osservazione Passiva Ambiente';
UPDATE ai_training_exercises SET title = 'Introductory Parallel Walking' WHERE title = 'Parallel Walking Introduttivo';
UPDATE ai_training_exercises SET title = 'Delayed Reward Patience' WHERE title = 'Pazienza Ricompensa Ritardata';
UPDATE ai_training_exercises SET title = 'Timed Obstacle Course' WHERE title = 'Percorso Ostacoli Temporizzato';
UPDATE ai_training_exercises SET title = 'Perfect Sleep Environment' WHERE title = 'Perfect Sleep Environment';
UPDATE ai_training_exercises SET title = 'Maintenance Planning' WHERE title = 'Pianificazione Mantenimento';
UPDATE ai_training_exercises SET title = 'Personalized Maintenance Plan' WHERE title = 'Piano Mantenimento Personalizzato';
UPDATE ai_training_exercises SET title = 'Positive Association with Strangers' WHERE title = 'Positive Association con Estranei';
UPDATE ai_training_exercises SET title = 'Calm Presence During Meals' WHERE title = 'Presenza Calma Durante i Pasti';
UPDATE ai_training_exercises SET title = 'Stranger Presence During Feeding' WHERE title = 'Presenza di Estranei Durante l\'Alimentazione';
UPDATE ai_training_exercises SET title = 'First "NO" Training and Redirection' WHERE title = 'Primo Training "NO" e Redirezione';
UPDATE ai_training_exercises SET title = 'Advanced Problem Solving' WHERE title = 'Problem Solving Avanzato';
UPDATE ai_training_exercises SET title = 'Progressive Muscle Relaxation' WHERE title = 'Progressive Muscle Relaxation';
UPDATE ai_training_exercises SET title = 'Safety Maintenance Protocol' WHERE title = 'Protocollo Mantenimento Sicurezza';
UPDATE ai_training_exercises SET title = 'Emergency Safety Protocol' WHERE title = 'Protocollo Sicurezza Emergenza';
UPDATE ai_training_exercises SET title = 'Complex Food Puzzle' WHERE title = 'Puzzle Alimentare Complesso';
UPDATE ai_training_exercises SET title = 'Advanced Puzzle Feeder' WHERE title = 'Puzzle Feeder Avanzato';
UPDATE ai_training_exercises SET title = 'Simple Puzzle Feeder' WHERE title = 'Puzzle Feeder Semplice';
UPDATE ai_training_exercises SET title = 'Reading Social Cues Training' WHERE title = 'Reading Social Cues Training';
UPDATE ai_training_exercises SET title = 'Real-World Simulation' WHERE title = 'Real-World Simulation';
UPDATE ai_training_exercises SET title = 'Real-World Social Application' WHERE title = 'Real-World Social Application';
UPDATE ai_training_exercises SET title = 'Active Prize Search' WHERE title = 'Ricerca Attiva Premi';
UPDATE ai_training_exercises SET title = 'Controlled Distance Reduction' WHERE title = 'Riduzione Distanza Controllata';
UPDATE ai_training_exercises SET title = 'Autonomous Relaxation' WHERE title = 'Rilassamento Autonomo';
UPDATE ai_training_exercises SET title = 'Post-Exercise Relaxation' WHERE title = 'Rilassamento Post-Esercizio';
UPDATE ai_training_exercises SET title = 'Guided Deep Relaxation' WHERE title = 'Rilassamento Profondo Guidato';
UPDATE ai_training_exercises SET title = 'Positive Associations Reinforcement' WHERE title = 'Rinforzo Associazioni Positive';
UPDATE ai_training_exercises SET title = 'Strategic Intermittent Reinforcement' WHERE title = 'Rinforzo Intermittente Strategico';
UPDATE ai_training_exercises SET title = 'Relaxing Sunset Ritual' WHERE title = 'Ritual del Tramonto Rilassante';
UPDATE ai_training_exercises SET title = 'Positive Pre-Trigger Rituals' WHERE title = 'Rituali Positivi Pre-Trigger';
UPDATE ai_training_exercises SET title = 'Controlled Toy Rotation' WHERE title = 'Rotazione Controllata dei Giocattoli';
UPDATE ai_training_exercises SET title = 'Multi-Pet Space and Resource Rotation' WHERE title = 'Rotazione Spazi e Risorse Multi-Pet';
UPDATE ai_training_exercises SET title = 'Independent Feeding Routine' WHERE title = 'Routine Alimentare Indipendente';
UPDATE ai_training_exercises SET title = 'Anti-Destructive Daily Routine' WHERE title = 'Routine Giornaliera Anti-Distruttiva';
UPDATE ai_training_exercises SET title = 'Neutral Departure Routine' WHERE title = 'Routine Neutra di Partenza';
UPDATE ai_training_exercises SET title = 'Relaxing Pre-Meal Routine' WHERE title = 'Routine Pre-Pasto Rilassante';
UPDATE ai_training_exercises SET title = 'Preventive Pre-Exit Routine' WHERE title = 'Routine Pre-Uscita Preventiva';
UPDATE ai_training_exercises SET title = 'Sanctuary Setup Ritual' WHERE title = 'Sanctuary Setup Rituale';
UPDATE ai_training_exercises SET title = 'Gradual Audio Intensity Scale' WHERE title = 'Scala Intensità Graduale Audio';
UPDATE ai_training_exercises SET title = 'Advanced Voluntary Exchange' WHERE title = 'Scambio Volontario Avanzato';
UPDATE ai_training_exercises SET title = 'Self-Regulation Skills' WHERE title = 'Self-Regulation Skills';
UPDATE ai_training_exercises SET title = 'Separation with Visual Barrier' WHERE title = 'Separazione con Barriera Visiva';
UPDATE ai_training_exercises SET title = '10-Minute Separations' WHERE title = 'Separazioni di 10 Minuti';
UPDATE ai_training_exercises SET title = '15-20 Minute Separations' WHERE title = 'Separazioni di 15-20 Minuti';
UPDATE ai_training_exercises SET title = '5-Minute Separations' WHERE title = 'Separazioni di 5 Minuti';
UPDATE ai_training_exercises SET title = 'Complex Command Sequences' WHERE title = 'Sequenze Comandi Complesse';
UPDATE ai_training_exercises SET title = 'Social Relaxation Session' WHERE title = 'Sessione di Relax Sociale';
UPDATE ai_training_exercises SET title = 'Complete Integration Session' WHERE title = 'Sessione Integrazione Completa';
UPDATE ai_training_exercises SET title = 'Final Positive Reinforcement Session' WHERE title = 'Sessione Rinforzo Positivo Finale';
UPDATE ai_training_exercises SET title = 'Anti-Destructive Environment Setup' WHERE title = 'Setup Ambiente Anti-Distruttivo';
UPDATE ai_training_exercises SET title = 'Multiple Self-Control Challenge' WHERE title = 'Sfida Autocontrollo Multipla';
UPDATE ai_training_exercises SET title = 'Multiple Choice Challenge' WHERE title = 'Sfida Scelta Multipla';
UPDATE ai_training_exercises SET title = 'Self-Managed Graduated Challenges' WHERE title = 'Sfide Graduate Autogestite';
UPDATE ai_training_exercises SET title = 'Guided Spontaneous Sharing' WHERE title = 'Sharing Spontaneo Guidato';
UPDATE ai_training_exercises SET title = 'Extended Absence Simulation' WHERE title = 'Simulazione Assenza Prolungata';
UPDATE ai_training_exercises SET title = 'Owner Absence Simulation' WHERE title = 'Simulazione Assenza Proprietario';
UPDATE ai_training_exercises SET title = 'Controlled Speed Slalom' WHERE title = 'Slalom Velocità Controllata';
UPDATE ai_training_exercises SET title = 'Sleep Command Training' WHERE title = 'Sleep Command Training';
UPDATE ai_training_exercises SET title = 'Sleep Quality Assessment' WHERE title = 'Sleep Quality Assessment';
UPDATE ai_training_exercises SET title = 'Slow Motion Feeding' WHERE title = 'Slow Motion Feeding';
UPDATE ai_training_exercises SET title = 'Social Skills in Controlled Environment' WHERE title = 'Social Skills in Ambiente Controllato';
UPDATE ai_training_exercises SET title = 'Sound Sleep Therapy' WHERE title = 'Sound Sleep Therapy';
UPDATE ai_training_exercises SET title = 'Stress Recovery Training' WHERE title = 'Stress Recovery Training';
UPDATE ai_training_exercises SET title = 'Supervised Social Play' WHERE title = 'Supervised Social Play';
UPDATE ai_training_exercises SET title = 'Positive Exchange Technique' WHERE title = 'Tecnica dello Scambio Positivo';
UPDATE ai_training_exercises SET title = 'Proactive Substitution Technique' WHERE title = 'Tecnica Sostituzione Proattiva';
UPDATE ai_training_exercises SET title = 'Basic Relaxation Techniques' WHERE title = 'Tecniche Rilassamento Base';
UPDATE ai_training_exercises SET title = '"Leave" Test with House Objects' WHERE title = 'Test "Lascia" con Oggetti Casa';
UPDATE ai_training_exercises SET title = 'Multiple Environments Test' WHERE title = 'Test Ambienti Multipli';
UPDATE ai_training_exercises SET title = 'Complete Self-Control Test' WHERE title = 'Test Completo Autocontrollo';
UPDATE ai_training_exercises SET title = 'Complete Consolidation Test' WHERE title = 'Test di Consolidamento Completo';
UPDATE ai_training_exercises SET title = 'Final Autonomy Test' WHERE title = 'Test Finale Autonomia';
UPDATE ai_training_exercises SET title = 'Initial Generalization Test' WHERE title = 'Test Generalizzazione Iniziale';
UPDATE ai_training_exercises SET title = 'Bowl Management Test' WHERE title = 'Test Gestione Ciotola';
UPDATE ai_training_exercises SET title = 'Complete Independence Test' WHERE title = 'Test Indipendenza Completa';
UPDATE ai_training_exercises SET title = 'Complete Integration Test' WHERE title = 'Test Integration Completa';
UPDATE ai_training_exercises SET title = 'Environmental Resilience Test' WHERE title = 'Test Resilienza Ambientale';
UPDATE ai_training_exercises SET title = 'Temptation Resistance Test' WHERE title = 'Test Resistenza alla Tentazione';
UPDATE ai_training_exercises SET title = 'Controlled Stress Test' WHERE title = 'Test Stress Controllato';
UPDATE ai_training_exercises SET title = 'Controlled Moderate Stress Test' WHERE title = 'Test Stress Moderato Controllato';
UPDATE ai_training_exercises SET title = 'Threshold Testing with Control' WHERE title = 'Testing Threshold con Control';
UPDATE ai_training_exercises SET title = 'Micro-Step Threshold Expansion' WHERE title = 'Threshold Expansion Micro-Step';
UPDATE ai_training_exercises SET title = 'Controlled Tug of War' WHERE title = 'Tiro alla Fune Controllato';
UPDATE ai_training_exercises SET title = 'Touch Training during Meals' WHERE title = 'Touch Training durante Pasti';
UPDATE ai_training_exercises SET title = 'Mental Tracking' WHERE title = 'Tracking Mentale';
UPDATE ai_training_exercises SET title = 'Positive "Add" Training' WHERE title = 'Training "Aggiungi" Positivo';
UPDATE ai_training_exercises SET title = '"Leave" Training with Food' WHERE title = 'Training "Lascia" con Cibo';
UPDATE ai_training_exercises SET title = '"Leave It" Training with Distractions' WHERE title = 'Training "Leave It" con Distrazioni';
UPDATE ai_training_exercises SET title = '"Look At Me" Training Under Threshold' WHERE title = 'Training "Look At Me" Sotto Soglia';
UPDATE ai_training_exercises SET title = '"Sit-Wait" Pre-Meal Training' WHERE title = 'Training "Seduto-Aspetta" Pre-Pasto';
UPDATE ai_training_exercises SET title = 'Emergency "Stop" Training' WHERE title = 'Training "Stop" di Emergenza';
UPDATE ai_training_exercises SET title = 'Positive Anticipation Training' WHERE title = 'Training Anticipazione Positiva';
UPDATE ai_training_exercises SET title = 'Self-Regulation Training' WHERE title = 'Training Autoregolazione';
UPDATE ai_training_exercises SET title = '"TAKE THIS" Command Training' WHERE title = 'Training Comando "PRENDI QUESTO"';
UPDATE ai_training_exercises SET title = 'Substitute Behavior Training' WHERE title = 'Training Comportamento Sostitutivo';
UPDATE ai_training_exercises SET title = 'Puzzle Toy Training' WHERE title = 'Training con Puzzle Toy';
UPDATE ai_training_exercises SET title = 'Space Sharing Training' WHERE title = 'Training Condivisione Spazio';
UPDATE ai_training_exercises SET title = 'Impulse Control Training' WHERE title = 'Training Controllo Impulsi';
UPDATE ai_training_exercises SET title = 'Home Independence Training' WHERE title = 'Training Indipendenza in Casa';
UPDATE ai_training_exercises SET title = 'Simultaneous Multi-Resource Training' WHERE title = 'Training Multi-Risorsa Simultanea';
UPDATE ai_training_exercises SET title = 'Controlled Portions Training' WHERE title = 'Training Porzioni Controllate';
UPDATE ai_training_exercises SET title = 'Temptation Resistance Training' WHERE title = 'Training Resistenza alla Tentazione';
UPDATE ai_training_exercises SET title = 'Conscious Satiety Training' WHERE title = 'Training Sazietà Consapevole';
UPDATE ai_training_exercises SET title = 'Trigger as Positivity Predictor' WHERE title = 'Trigger Come Predittore di Positività';
UPDATE ai_training_exercises SET title = 'Initial Progress Evaluation' WHERE title = 'Valutazione Progressi Iniziali';
UPDATE ai_training_exercises SET title = 'Weekly Progress Evaluation' WHERE title = 'Valutazione Progressi Settimanali';
UPDATE ai_training_exercises SET title = 'Realistic Trigger Variations' WHERE title = 'Variazioni Trigger Realistiche';