-- Crea tutti gli esercizi per il protocollo "Controllo Aggressività Reattiva" (7 giorni, 21 esercizi)
DO $$
DECLARE
    protocol_uuid UUID;
BEGIN
    -- Trova l'ID del protocollo per l'aggressività
    SELECT id INTO protocol_uuid 
    FROM ai_training_protocols 
    WHERE category = 'aggressivita'
    LIMIT 1;
    
    IF protocol_uuid IS NOT NULL THEN
        INSERT INTO ai_training_exercises (protocol_id, day_number, title, description, instructions, exercise_type, duration_minutes, materials) VALUES
        -- GIORNO 1
        (protocol_uuid, 1, 'Identificazione Trigger di Aggressività', 'Mappatura completa di tutti i fattori scatenanti', ARRAY['Osserva e registra TUTTI i momenti in cui il pet mostra aggressività', 'Nota: ora del giorno, situazione, persone/animali presenti, stimoli ambientali', 'Classifica intensità da 1-10 per ogni episodio', 'Identifica pattern: ci sono trigger ricorrenti?', 'FONDAMENTALE: non intervenire oggi, solo osservare e documentare'], 'behavioral', 30, ARRAY['Diario dettagliato', 'Cronometro', 'Scala intensità 1-10']),
        (protocol_uuid, 1, 'Comando "Stop" di Emergenza Base', 'Insegnare comando di interruzione immediata', ARRAY['Insegna comando "STOP" o "BASTA" con voce ferma ma non urlata', 'Pratica in situazioni NON aggressive, quando fa cose normali', 'Quando dice stop, il pet deve fermarsi immediatamente', 'Premia ogni volta che si ferma al comando', 'Questo comando deve diventare automatico prima di usarlo in crisi'], 'behavioral', 15, ARRAY['Treats di alto valore', 'Voce ferma e sicura']),
        (protocol_uuid, 1, 'Valutazione Soglia di Eccitazione', 'Determinare quando il pet passa da calmo ad aggressivo', ARRAY['Osserva i segnali che precedono l''aggressività', 'Rigidità corporea, sguardo fisso, ringhio sottile, pelo rizzato', 'Identifica il "punto di non ritorno" - quando è troppo tardi per intervenire', 'Trova il momento ideale per intervento: PRIMA che diventi aggressivo', 'Documenta questi "segnali di allarme" per ogni situazione'], 'behavioral', 20, ARRAY['Lista segnali di allarme', 'Osservazione attenta']),

        -- GIORNO 2
        (protocol_uuid, 2, 'Desensibilizzazione a Distanza Trigger Primario', 'Esposizione controllata al trigger principale a distanza sicura', ARRAY['Identifica il trigger #1 dal giorno 1', 'Esponilo a GRANDE distanza - abbastanza lontano da non causare reazione', 'Se resta calmo, premia immediatamente', 'Se mostra segni di agitazione, aumenta ancora la distanza', 'Durata: max 10 minuti per evitare stress cumulativo'], 'behavioral', 25, ARRAY['Trigger controllato', 'Distanza misurata', 'Treats premium']),
        (protocol_uuid, 2, 'Rinforzo Comando "Guardami" Sotto Stress', 'Mantenere attenzione anche con distrazioni', ARRAY['Pratica "guardami" con distrazioni lievi', 'Il pet deve focalizzarsi su di te anche quando è leggermente stimolato', 'Inizia con distrazioni minime, aumenta gradualmente', 'Premia intensamente ogni contatto visivo mantenuto', 'Questo comando sarà cruciale per gestire episodi aggressivi'], 'behavioral', 15, ARRAY['Distrazioni graduate', 'Treats irresistibili']),
        (protocol_uuid, 2, 'Tecnica "Trova il Posto Sicuro"', 'Insegnare al pet dove andare quando è sovrastimolato', ARRAY['Designa un posto specifico come "rifugio sicuro" (cuccia, tappeto, angolo)', 'Insegna comando "posto sicuro" o "casa"', 'Pratica quando è calmo: comando → va al posto → mega premio', 'Il posto sicuro deve diventare associato a calma e sicurezza', 'Mai usare il posto sicuro come punizione'], 'behavioral', 20, ARRAY['Area designata come rifugio', 'Comando specifico', 'Premi speciali']),

        -- GIORNO 3
        (protocol_uuid, 3, 'Counter-Conditioning Trigger Secondario', 'Cambiare associazione emotiva con secondo trigger più importante', ARRAY['Usa il trigger #2 identificato il primo giorno', 'Presenta trigger + cibo/gioco fantastico simultaneamente', 'Il pet deve iniziare ad associare il trigger a cose positive', 'Se mostra stress, il trigger è troppo vicino/intenso', 'Obiettivo: trigger = aspettativa di cose buone'], 'behavioral', 30, ARRAY['Secondo trigger identificato', 'Ricompense straordinarie']),
        (protocol_uuid, 3, 'Controllo Impulsi "Aspetta" Avanzato', 'Autocontrollo in situazioni di eccitazione', ARRAY['Pratica "aspetta" con stimoli eccitanti (cibo, giochi, doorbell)', 'Il pet deve imparare che l''eccitazione non giustifica perdita di controllo', 'Inizia con stimoli leggeri, aumenta intensità gradualmente', 'Non premiare mai comportamenti impulsivi', 'Premia solo autocontrollo e calma'], 'behavioral', 20, ARRAY['Stimoli eccitanti controllati', 'Timer per "aspetta"']),
        (protocol_uuid, 3, 'Redirecting Aggressività in Gioco', 'Canalizzare energia aggressiva in attività positive', ARRAY['Quando noti primi segni di agitazione, redirect immediato in gioco intenso', 'Usa giochi che permettono "sfogare": tira e molla, giochi da masticare', 'L''energia aggressiva diventa energia di gioco', 'Termina sempre il gioco prima che il pet si stanchi troppo', 'Questo insegna: agitazione = tempo di gioco, non di aggressione'], 'behavioral', 25, ARRAY['Giochi per sfogare energia', 'Timing perfetto per redirect']),

        -- GIORNO 4
        (protocol_uuid, 4, 'Gestione Spazio Personale', 'Insegnare rispetto dei confini senza aggressività', ARRAY['Pratica esercizi dove il pet deve rispettare spazio senza ringhiare', 'Usa barriere fisiche (cancelletti) invece di punizioni', 'Premia ogni volta che rispetta lo spazio senza proteste', 'Se protesta, non cedere ma non punire - semplicemente mantieni confine', 'Gradualmente riduci barriere fisiche sostituendole con controllo verbale'], 'behavioral', 35, ARRAY['Barriere fisiche temporanee', 'Spazi delimitati']),
        (protocol_uuid, 4, 'Comando "Rilasciare" per Possessività', 'Gestire protezione eccessiva di oggetti/cibo', ARRAY['Insegna "lascia" o "rilascia" con oggetti di basso valore', 'SCAMBIA sempre l''oggetto con qualcosa di ancora più buono', 'Non strappare mai oggetti dalle fauci', 'Pratica con oggetti di valore crescente', 'Il pet deve imparare: rilasciare = ottenere qualcosa di meglio'], 'behavioral', 20, ARRAY['Oggetti di valore scalare', 'Scambi sempre vantaggiosi']),
        (protocol_uuid, 4, 'Desensibilizzazione Manipolazione Fisica', 'Tollerare tocco senza reazioni aggressive', ARRAY['Inizia con tocchi brevissimi in zone non sensibili', 'Tocco + treat immediato + lode', 'Gradualmente aumenta durata e estendi a zone più sensibili', 'Se mostra tensione, torna a livello precedente', 'Mai forzare - sempre associare tocco a piacere'], 'behavioral', 15, ARRAY['Approccio graduale al tocco', 'Treats per associazione positiva']),

        -- GIORNO 5
        (protocol_uuid, 5, 'Simulazione Situazioni Stressanti Controllate', 'Pratica gestione in situazioni che tipicamente causano aggressività', ARRAY['Ricrea situazioni trigger ma in versione molto attenuata', 'Mantieni sempre controllo totale della situazione', 'Al primo segno di stress, usa comandi appresi (stop, guardami, posto sicuro)', 'Obiettivo: il pet impara che può gestire stress senza aggressività', 'Termina sempre con successo e grande celebrazione'], 'behavioral', 40, ARRAY['Situazioni controllate', 'Tutti i comandi appresi']),
        (protocol_uuid, 5, 'Rinforzo Positivo Comportamenti Alternativi', 'Premiare comportamenti opposti all''aggressività', ARRAY['Identifica comportamenti incompatibili con aggressività: seduto calmo, sdraiato rilassato, gioco gentile', 'Premia intensamente questi comportamenti ogni volta che li vedi', 'Cerca attivamente questi comportamenti per rinforzarli', 'Il pet deve scoprire che essere calmo e gentile paga molto di più', 'Crea "banca comportamenti" da rinforzare'], 'behavioral', 20, ARRAY['Lista comportamenti alternativi', 'Sistema di premi differenziato']),
        (protocol_uuid, 5, 'Test Soglia di Tolleranza', 'Verificare progressi nella gestione dei trigger', ARRAY['Testa i trigger del primo giorno a distanza leggermente ridotta', 'Monitora attentamente i segnali di stress', 'Se resta calmo, puoi avvicinare di poco il trigger', 'Se mostra stress, torna immediatamente a distanza sicura', 'Documenta i progressi: riesce a tollerare trigger più vicini di prima?'], 'behavioral', 25, ARRAY['Trigger originali', 'Misurazione distanze', 'Documentazione progressi']),

        -- GIORNO 6
        (protocol_uuid, 6, 'Gestione Interazioni Controllate', 'Pratica con altri animali/persone in sicurezza', ARRAY['Organizza incontro controllato con animale/persona molto calma', 'Mantieni sempre controllo con guinzaglio/barriere', 'Usa tutti i comandi appresi per gestire l''interazione', 'Durata breve: 5-10 minuti massimo', 'Focus su successo, non su durata dell''interazione'], 'behavioral', 45, ARRAY['Partner molto esperto e calmo', 'Controlli di sicurezza']),
        (protocol_uuid, 6, 'Consolidamento Emergenza Protocols', 'Ripasso procedure per gestire crisi aggressive', ARRAY['Pratica sequenza: riconoscere segnali → comando stop → redirect → posto sicuro', 'Simula (senza causare stress reale) situazioni di emergenza', 'Il pet deve rispondere automaticamente alla sequenza', 'Tu devi eseguire la sequenza senza panico o frustrazione', 'Questo è il "piano di emergenza" per situazioni reali'], 'behavioral', 20, ARRAY['Sequenza di comandi memorizzata', 'Simulazioni sicure']),
        (protocol_uuid, 6, 'Rilassamento Profondo Post-Stress', 'Insegnare recupero rapido dopo situazioni stressanti', ARRAY['Dopo ogni esercizio stressante, pratica rilassamento immediato', 'Massaggi gentili, vocalizzazioni calme, ambiente tranquillo', 'Il pet deve imparare a "resettare" rapidamente dopo stress', 'Tempo di rilassamento = tempo per elaborare l''esperienza positivamente', 'Questa fase è cruciale quanto l''addestramento attivo'], 'behavioral', 25, ARRAY['Ambiente ultra-tranquillo', 'Tecniche di rilassamento']),

        -- GIORNO 7
        (protocol_uuid, 7, 'Test Finale Situazione Reale', 'Valutazione competenze in scenario realistico', ARRAY['Organizza situazione che storicamente causava aggressività', 'Usa tutte le tecniche apprese per gestire la situazione', 'Non cercare la perfezione - cerca il miglioramento rispetto al primo giorno', 'Intervieni preventivamente usando segnali di allarme identificati', 'Questo è il test di "laurea" del protocollo'], 'behavioral', 50, ARRAY['Situazione reale controllata', 'Tutte le tecniche apprese']),
        (protocol_uuid, 7, 'Valutazione Progressi Complessivi', 'Analisi completa dei miglioramenti ottenuti', ARRAY['Confronta comportamento aggressivo di oggi vs. primo giorno', 'Documenta: frequenza episodi, intensità, durata, recovery time', 'Identifica successi e aree che necessitano ancora lavoro', 'Questi dati determineranno se ripetere il protocollo o passare oltre', 'Sii realistico: l''aggressività richiede tempo per essere modificata'], 'behavioral', 20, ARRAY['Dati iniziali per confronto', 'Analisi obiettiva']),
        (protocol_uuid, 7, 'Pianificazione Gestione Lungo Termine', 'Strategia per mantenere progressi e continuare miglioramento', ARRAY['Crea piano di mantenimento per evitare regressioni', 'Stabilisci routine di pratica settimanale per mantenere controllo', 'Identifica situazioni che richiedono ancora supervisione', 'Pianifica quando introdurre nuove sfide gradualmente', 'Ricorda: gestire aggressività è un percorso continuo, non una cura unica'], 'behavioral', 30, ARRAY['Piano di mantenimento scritto', 'Strategia a lungo termine']);
    END IF;
END $$;