-- MEGA TRADUZIONE PARTE 3: ULTIMI TITOLI
-- Completa tutti i titoli rimanenti degli esercizi

UPDATE ai_training_exercises SET title = 'Advanced Problem Solving' WHERE title = 'Problem Solving Avanzato';
UPDATE ai_training_exercises SET title = 'Safety Maintenance Protocol' WHERE title = 'Protocollo Mantenimento Sicurezza';
UPDATE ai_training_exercises SET title = 'Emergency Safety Protocol' WHERE title = 'Protocollo Sicurezza Emergenza';
UPDATE ai_training_exercises SET title = 'Complex Food Puzzle' WHERE title = 'Puzzle Alimentare Complesso';
UPDATE ai_training_exercises SET title = 'Advanced Puzzle Feeder' WHERE title = 'Puzzle Feeder Avanzato';
UPDATE ai_training_exercises SET title = 'Simple Puzzle Feeder' WHERE title = 'Puzzle Feeder Semplice';
UPDATE ai_training_exercises SET title = 'Active Prize Search' WHERE title = 'Ricerca Attiva Premi';
UPDATE ai_training_exercises SET title = 'Controlled Distance Reduction' WHERE title = 'Riduzione Distanza Controllata';
UPDATE ai_training_exercises SET title = 'Autonomous Relaxation' WHERE title = 'Rilassamento Autonomo';
UPDATE ai_training_exercises SET title = 'Post-Exercise Relaxation' WHERE title = 'Rilassamento Post-Esercizio';
UPDATE ai_training_exercises SET title = 'Guided Deep Relaxation' WHERE title = 'Rilassamento Profondo Guidato';
UPDATE ai_training_exercises SET title = 'Positive Associations Reinforcement' WHERE title = 'Rinforzo Associazioni Positive';
UPDATE ai_training_exercises SET title = 'Strategic Intermittent Reinforcement' WHERE title = 'Rinforzo Intermittente Strategico';
UPDATE ai_training_exercises SET title = 'Positive Pre-Trigger Rituals' WHERE title = 'Rituali Positivi Pre-Trigger';
UPDATE ai_training_exercises SET title = 'Controlled Toy Rotation' WHERE title = 'Rotazione Controllata dei Giocattoli';
UPDATE ai_training_exercises SET title = 'Multi-Pet Space and Resource Rotation' WHERE title = 'Rotazione Spazi e Risorse Multi-Pet';
UPDATE ai_training_exercises SET title = 'Independent Feeding Routine' WHERE title = 'Routine Alimentare Indipendente';
UPDATE ai_training_exercises SET title = 'Anti-Destructive Daily Routine' WHERE title = 'Routine Giornaliera Anti-Distruttiva';
UPDATE ai_training_exercises SET title = 'Neutral Departure Routine' WHERE title = 'Routine Neutra di Partenza';
UPDATE ai_training_exercises SET title = 'Relaxing Pre-Meal Routine' WHERE title = 'Routine Pre-Pasto Rilassante';
UPDATE ai_training_exercises SET title = 'Preventive Pre-Exit Routine' WHERE title = 'Routine Pre-Uscita Preventiva';
UPDATE ai_training_exercises SET title = 'Gradual Audio Intensity Scale' WHERE title = 'Scala Intensità Graduale Audio';
UPDATE ai_training_exercises SET title = 'Advanced Voluntary Exchange' WHERE title = 'Scambio Volontario Avanzato';
UPDATE ai_training_exercises SET title = 'Separation with Visual Barrier' WHERE title = 'Separazione con Barriera Visiva';
UPDATE ai_training_exercises SET title = '10-Minute Separations' WHERE title = 'Separazioni di 10 Minuti';
UPDATE ai_training_exercises SET title = '15-20 Minute Separations' WHERE title = 'Separazioni di 15-20 Minuti';
UPDATE ai_training_exercises SET title = '5-Minute Separations' WHERE title = 'Separazioni di 5 Minuti';
UPDATE ai_training_exercises SET title = 'Complex Command Sequences' WHERE title = 'Sequenze Comandi Complesse';
UPDATE ai_training_exercises SET title = 'Social Relaxation Session' WHERE title = 'Sessione di Relax Sociale';
UPDATE ai_training_exercises SET title = 'Complete Integration Session' WHERE title = 'Sessione Integrazione Completa';
UPDATE ai_training_exercises SET title = 'Final Positive Reinforcement Session' WHERE title = 'Sessione Rinforzo Positivo Finale';
UPDATE ai_training_exercises SET title = 'Anti-Destructive Environment Setup' WHERE title = 'Setup Ambiente Anti-Distruttivo';
UPDATE ai_training_exercises SET title = 'Multiple Self-Control Challenge' WHERE title = 'Sfida Autocontrollo Multipla';
UPDATE ai_training_exercises SET title = 'Multiple Choice Challenge' WHERE title = 'Sfida Scelta Multipla';
UPDATE ai_training_exercises SET title = 'Self-Managed Graduated Challenges' WHERE title = 'Sfide Graduate Autogestite';
UPDATE ai_training_exercises SET title = 'Guided Spontaneous Sharing' WHERE title = 'Sharing Spontaneo Guidato';
UPDATE ai_training_exercises SET title = 'Extended Absence Simulation' WHERE title = 'Simulazione Assenza Prolungata';
UPDATE ai_training_exercises SET title = 'Owner Absence Simulation' WHERE title = 'Simulazione Assenza Proprietario';
UPDATE ai_training_exercises SET title = 'Controlled Speed Slalom' WHERE title = 'Slalom Velocità Controllata';
UPDATE ai_training_exercises SET title = 'Social Skills in Controlled Environment' WHERE title = 'Social Skills in Ambiente Controllato';
UPDATE ai_training_exercises SET title = 'Positive Exchange Technique' WHERE title = 'Tecnica dello Scambio Positivo';
UPDATE ai_training_exercises SET title = 'Proactive Substitution Technique' WHERE title = 'Tecnica Sostituzione Proattiva';
UPDATE ai_training_exercises SET title = 'Basic Relaxation Techniques' WHERE title = 'Tecniche Rilassamento Base';
UPDATE ai_training_exercises SET title = 'Leave Test with House Objects' WHERE title = 'Test "Lascia" con Oggetti Casa';
UPDATE ai_training_exercises SET title = 'Multiple Environments Test' WHERE title = 'Test Ambienti Multipli';
UPDATE ai_training_exercises SET title = 'Complete Self-Control Test' WHERE title = 'Test Completo Autocontrollo';
UPDATE ai_training_exercises SET title = 'Complete Consolidation Test' WHERE title = 'Test di Consolidamento Completo';
UPDATE ai_training_exercises SET title = 'Final Autonomy Test' WHERE title = 'Test Finale Autonomia';
UPDATE ai_training_exercises SET title = 'Initial Generalization Test' WHERE title = 'Test Generalizzazione Iniziale';
UPDATE ai_training_exercises SET title = 'Bowl Management Test' WHERE title = 'Test Gestione Ciotola';
UPDATE ai_training_exercises SET title = 'Complete Independence Test' WHERE title = 'Test Indipendenza Completa';
UPDATE ai_training_exercises SET title = 'Complete Integration Test' WHERE title = 'Test Integration Completa';
UPDATE ai_training_exercises SET title = 'Environmental Resilience Test' WHERE title = 'Test Resilienza Ambientale';
UPDATE ai_training_exercises SET title = 'Temptation Resistance Test' WHERE title = 'Test Resistenza alla Tentazione';
UPDATE ai_training_exercises SET title = 'Controlled Stress Test' WHERE title = 'Test Stress Controllato';
UPDATE ai_training_exercises SET title = 'Controlled Moderate Stress Test' WHERE title = 'Test Stress Moderato Controllato';
UPDATE ai_training_exercises SET title = 'Threshold Testing with Control' WHERE title = 'Testing Threshold con Control';
UPDATE ai_training_exercises SET title = 'Micro-Step Threshold Expansion' WHERE title = 'Threshold Expansion Micro-Step';
UPDATE ai_training_exercises SET title = 'Controlled Tug of War' WHERE title = 'Tiro alla Fune Controllato';
UPDATE ai_training_exercises SET title = 'Touch Training during Meals' WHERE title = 'Touch Training durante Pasti';
UPDATE ai_training_exercises SET title = 'Mental Tracking' WHERE title = 'Tracking Mentale';