-- MEGA TRADUZIONE DESCRIZIONI PARTE 1
-- Traduce TUTTE le descrizioni degli esercizi dal italiano all'inglese

-- Descrizioni degli esercizi motivazionali con emoji
UPDATE ai_training_exercises SET description = 'Create new pleasant routine to associate specific moments with positive experiences.' WHERE description = 'Creazione di nuova routine piacevole per associare momenti specifici a esperienze positive.';
UPDATE ai_training_exercises SET description = 'Visual stimulation through colorful objects to reactivate interest and visual attention.' WHERE description = 'Stimolazione visiva attraverso oggetti colorati per riattivare l''interesse e l''attenzione visiva.';
UPDATE ai_training_exercises SET description = 'Basic path with low obstacles to stimulate coordination and confidence in movements.' WHERE description = 'Percorso base con ostacoli bassi per stimolare coordinazione e fiducia nei movimenti.';
UPDATE ai_training_exercises SET description = 'Gradual stimulation through natural scents to reactivate senses and interest in the surrounding environment.' WHERE description = 'Stimolazione graduale attraverso profumi naturali per riattivare i sensi e l''interesse verso l''ambiente circostante.';
UPDATE ai_training_exercises SET description = 'Gentle exploration of new house corners to stimulate curiosity and voluntary movement.' WHERE description = 'Esplorazione dolce di nuovi angoli della casa per stimolare curiosità e movimento volontario.';
UPDATE ai_training_exercises SET description = 'Box opening game to stimulate curiosity and persistence through hidden rewards.' WHERE description = 'Gioco di apertura scatole per stimolare curiosità e persistenza attraverso ricompense nascoste.';
UPDATE ai_training_exercises SET description = 'Session to recognize and celebrate all progress made during the protocol.' WHERE description = 'Sessione di riconoscimento e celebrazione di tutti i progressi fatti durante il protocollo.';
UPDATE ai_training_exercises SET description = 'Free playtime with different materials to stimulate creativity and spontaneous expression.' WHERE description = 'Tempo di gioco libero con materiali diversi per stimolare creatività e espressione spontanea.';
UPDATE ai_training_exercises SET description = 'Shared games to rebuild the pleasure of interaction and collaboration.' WHERE description = 'Giochi condivisi per ricostruire il piacere dell''interazione e della collaborazione.';
UPDATE ai_training_exercises SET description = 'Teaching simple tricks to increase self-esteem and positive connection with training.' WHERE description = 'Insegnamento di trick semplici per aumentare autostima e connessione positiva con l''addestramento.';
UPDATE ai_training_exercises SET description = 'Gentle precision exercise to improve coordination and concentration through simple targets.' WHERE description = 'Esercizio di precisione dolce per migliorare coordinazione e concentrazione attraverso target semplici.';
UPDATE ai_training_exercises SET description = 'Choice game between different options to stimulate decision-making process and increase confidence.' WHERE description = 'Gioco di scelta tra opzioni diverse per stimolare processo decisionale e aumentare fiducia.';
UPDATE ai_training_exercises SET description = 'Gradual auditory stimulation to reactivate attention and interest in environmental sounds.' WHERE description = 'Stimolazione uditiva graduale per riattivare l''attenzione e l''interesse verso i suoni dell''ambiente.';
UPDATE ai_training_exercises SET description = 'Gradual introduction to ball play to stimulate natural instincts and coordinated movement.' WHERE description = 'Introduzione graduale al gioco con palla per stimolare istinti naturali e movimento coordinato.';
UPDATE ai_training_exercises SET description = 'Gradual introduction to positive social interactions to rebuild trust in relationships.' WHERE description = 'Introduzione graduale a interazioni sociali positive per ricostruire fiducia nelle relazioni.';
UPDATE ai_training_exercises SET description = 'Gentle massage to reactivate positive connection with human touch and stimulate wellbeing.' WHERE description = 'Massaggio delicato per riattivare la connessione positiva con il tocco umano e stimolare benessere.';
UPDATE ai_training_exercises SET description = 'Planning session to maintain and further develop regained motivation.' WHERE description = 'Sessione di pianificazione per mantenere e sviluppare ulteriormente la motivazione riconquistata.';
UPDATE ai_training_exercises SET description = 'Teaching basic action sequences to develop memory and sustained concentration.' WHERE description = 'Insegnamento di sequenze base di azioni per sviluppare memoria e concentrazione sostenuta.';
UPDATE ai_training_exercises SET description = 'Guided search of hidden objects to develop concentration and active use of smell.' WHERE description = 'Ricerca guidata di oggetti nascosti per sviluppare concentrazione e utilizzo attivo dell''olfatto.';
UPDATE ai_training_exercises SET description = 'Basic treasure hunt to stimulate curiosity and voluntary movement through smell.' WHERE description = 'Caccia al tesoro base per stimolare curiosità e movimento volontario attraverso l''olfatto.';
UPDATE ai_training_exercises SET description = 'Introduction to simple food puzzles to stimulate problem-solving and maintain prolonged interest.' WHERE description = 'Introduzione a puzzle alimentari semplici per stimolare problem-solving e mantenere l''interesse prolungato.';
UPDATE ai_training_exercises SET description = 'Tactile stimulation through different surfaces to awaken curiosity and pleasure of contact.' WHERE description = 'Stimolazione tattile attraverso diverse superfici per risvegliare la curiosità e il piacere del contatto.';
UPDATE ai_training_exercises SET description = 'Final evaluation of acquired abilities and level of motivation reached.' WHERE description = 'Valutazione finale delle capacità acquisite e del livello di motivazione raggiunto.';
UPDATE ai_training_exercises SET description = 'Gentle and gradual movement to reactivate muscles and stimulate circulation without fatigue.' WHERE description = 'Movimento dolce e graduale per riattivare la muscolatura e stimolare la circolazione senza affaticare.';