-- Esercizi per tutti i protocolli rimanenti

-- PROTOCOLLO 2: Stop Comportamenti Distruttivi (12 giorni)
INSERT INTO ai_training_exercises (protocol_id, day_number, title, description, exercise_type, duration_minutes, instructions, materials)
SELECT p.id, exercises.day_num, exercises.title, exercises.description, 'behavioral', exercises.duration, exercises.instructions::text[], exercises.materials::text[]
FROM ai_training_protocols p,
(VALUES
  (1, 'Identificazione Trigger', 'Mappare situazioni che scatenano comportamenti distruttivi', 30,
   ARRAY['Osservare senza intervenire', 'Annotare orari e situazioni', 'Identificare pattern', 'Non punire, solo osservare'],
   ARRAY['Quaderno osservazioni']),
  (2, 'Reindirizzamento Masticazione', 'Fornire alternative appropriate per masticare', 20,
   ARRAY['Sostituire oggetto proibito con gioco da masticare', 'Lodare quando usa oggetto corretto', 'Ignorare masticazione inappropriata', 'Rotazione giochi ogni 3 giorni'],
   ARRAY['Giochi da masticare', 'Spray amaro']),
  (3, 'Controllo Accesso Ambientale', 'Gestire ambiente per prevenire distruzione', 15,
   ARRAY['Rimuovere tentazioni alla portata', 'Creare zone sicure', 'Supervisionare sempre inizialmente', 'Aumentare gradualmente libertà'],
   ARRAY['Barriere fisiche', 'Box/recinto']),
  (4, 'Stimolazione Mentale Intensiva', 'Stancare mentalmente per ridurre energia distruttiva', 25,
   ARRAY['Puzzle feeder per tutti i pasti', 'Nascondere cibo in casa', 'Giochi rotanti ogni ora', 'Sessioni brevi ma frequenti'],
   ARRAY['Puzzle feeder', 'Giochi interattivi']),
  (5, 'Comando "Lascia"', 'Insegnare a mollare oggetti su richiesta', 20,
   ARRAY['Offrire scambio vantaggioso', 'Mai togliere con forza', 'Comando "lascia" + premio', 'Praticare con oggetti non importanti'],
   ARRAY['Oggetti vari', 'Premi di alto valore']),
  (6, 'Gestione Energia Fisica', 'Scaricare energia attraverso attività appropriate', 30,
   ARRAY['Esercizio fisico intenso mattina', 'Giochi di riporto', 'Camminate lunghe', 'Stanchezza fisica prima di lasciarlo solo'],
   ARRAY['Palla', 'Guinzaglio lungo']),
  (7, 'Tecniche Anti-Scavo', 'Prevenire e reindirizzare comportamenti di scavo', 25,
   ARRAY['Creare zona scavo autorizzata', 'Nascondere tesori nella zona permessa', 'Bloccare accesso ad aree proibite', 'Premiare scavo corretto'],
   ARRAY['Sabbia/terra', 'Premi nascosti', 'Reti protettive']),
  (8, 'Controllo Separazione', 'Gestire comportamenti distruttivi quando resta solo', 20,
   ARRAY['Uscite brevissime iniziali (5 min)', 'Aumentare gradualmente durata', 'Lasciare giochi speciali', 'Rientrare solo se calmo'],
   ARRAY['Giochi Kong', 'Camera sorveglianza']),
  (9, 'Rinforzo Comportamenti Positivi', 'Aumentare frequenza di comportamenti desiderati', 15,
   ARRAY['Premiare immediatamente comportamenti calmi', 'Ignorare comportamenti distruttivi', 'Attenzione solo per azioni positive', 'Consistenza familiare'],
   ARRAY['Premi vari', 'Clicker']),
  (10, 'Gestione Stress Ambientale', 'Ridurre fattori di stress che causano distruzione', 25,
   ARRAY['Routine giornaliera fissa', 'Spazi comfort sempre accessibili', 'Minimizzare cambiamenti', 'Diffusore feromoni'],
   ARRAY['Diffusore feromoni', 'Coperte comfort']),
  (11, 'Test Resistenza', 'Verificare controllo in situazioni provocatorie', 30,
   ARRAY['Lasciare oggetti tentanti sotto controllo', 'Simulare assenze brevi', 'Aumentare difficoltà gradualmente', 'Intervenire solo se necessario'],
   ARRAY['Oggetti test', 'Telecamera']),
  (12, 'Consolidamento e Mantenimento', 'Stabilizzare i progressi ottenuti', 20,
   ARRAY['Review completa di tutti i trigger', 'Test situazioni reali', 'Piano mantenimento lungo termine', 'Celebrare successi'],
   ARRAY['Tutti i materiali precedenti'])
) AS exercises(day_num, title, description, duration, instructions, materials)
WHERE p.title = 'Stop Comportamenti Distruttivi';

-- PROTOCOLLO 3: Superare Fobie e Paure Specifiche (14 giorni)
INSERT INTO ai_training_exercises (protocol_id, day_number, title, description, exercise_type, duration_minutes, instructions, materials)
SELECT p.id, exercises.day_num, exercises.title, exercises.description, 'behavioral', exercises.duration, exercises.instructions::text[], exercises.materials::text[]
FROM ai_training_protocols p,
(VALUES
  (1, 'Mappatura delle Paure', 'Identificare e catalogare specifiche fobie e trigger', 30,
   ARRAY['Testare reazioni a diversi stimoli', 'Annotare intensità delle reazioni', 'Creare scala di gravità 1-10', 'Non forzare esposizioni'],
   ARRAY['Lista stimoli', 'Quaderno valutazioni']),
  (2, 'Creazione Spazio Sicuro', 'Stabilire area di comfort per sessioni di lavoro', 20,
   ARRAY['Identificare zona più tranquilla casa', 'Aggiungere comfort (coperte, giochi)', 'Praticare rilassamento in zona sicura', 'Associare zona a esperienze positive'],
   ARRAY['Coperte morbide', 'Giochi preferiti', 'Cuscini']),
  (3, 'Contro-condizionamento Base', 'Associare stimoli di paura a esperienze positive', 25,
   ARRAY['Presentare stimolo a distanza sicura', 'Offrire premi di alto valore simultaneamente', 'Mantenere sotto soglia di paura', 'Sessioni brevi (5-10 min)'],
   ARRAY['Premi speciali', 'Giochi di valore', 'Fonte stimolo controllata']),
  (4, 'Tecniche di Rilassamento', 'Insegnare comandi per indurre calma', 30,
   ARRAY['Comando "respira" con respirazione lenta', 'Massaggi delicati', 'Musica calmante', 'Posizione "relax" prolungata'],
   ARRAY['Musica rilassante', 'Oli essenziali pet-safe']),
  (5, 'Desensibilizzazione Graduale Livello 1', 'Esposizione molto lieve al trigger principale', 20,
   ARRAY['Stimolo al minimo volume/intensità', 'Distanza massima possibile', 'Premiare calma immediatamente', 'Interrompere se stress aumenta'],
   ARRAY['Controllo volume', 'Premi continui', 'Cronometro']),
  (6, 'Rinforzo Positivo Intensivo', 'Aumentare associazioni positive', 15,
   ARRAY['Ogni esposizione = festa di premi', 'Coinvolgere tutti i sensi positivamente', 'Creare rituali piacevoli', 'Celebrare ogni piccolo progresso'],
   ARRAY['Varietà di premi', 'Giochi nuovi', 'Interazioni sociali positive']),
  (7, 'Desensibilizzazione Livello 2', 'Incremento graduale intensità stimolo', 25,
   ARRAY['Aumentare volume/intensità del 10%', 'Ridurre distanza di 1 metro', 'Mantenere associazioni positive', 'Procedere solo se precedente livello è stabile'],
   ARRAY['Controlli precisi stimolo', 'Metro da misura', 'Premi di qualità']),
  (8, 'Gestione Regressioni', 'Protocollo per gestire ricadute', 20,
   ARRAY['Identificare segni di stress precoce', 'Tornare al livello precedente se necessario', 'Non punire reazioni di paura', 'Mantenere pazienza e costanza'],
   ARRAY['Scala di stress', 'Piano di emergenza']),
  (9, 'Esposizione Controllata', 'Simulazioni realistiche in ambiente sicuro', 30,
   ARRAY['Creare scenari realistici ma controllati', 'Avere sempre via di fuga disponibile', 'Sessioni più lunghe ma meno intense', 'Coinvolgere famiglia nel processo'],
   ARRAY['Oggetti simulazione', 'Spazio ampio', 'Supporto familiare']),
  (10, 'Generalizzazione Ambienti', 'Applicare apprendimenti in luoghi diversi', 25,
   ARRAY['Praticare in ambienti diversi', 'Iniziare da luoghi familiari', 'Aumentare gradualmente novità ambientale', 'Mantenere routine di sicurezza'],
   ARRAY['Trasportino confortevole', 'Kit premi portatile']),
  (11, 'Test Progressivi', 'Valutare miglioramenti con sfide graduate', 20,
   ARRAY['Aumentare intensità in modo controllato', 'Documentare progressi oggettivamente', 'Celebrare ogni successo', 'Adattare piano se necessario'],
   ARRAY['Camera per documentare', 'Scala progressi']),
  (12, 'Integrazione Sociale', 'Esposizione a stimoli in contesti sociali', 30,
   ARRAY['Introdurre presenza di altre persone/animali', 'Mantenere controllo della situazione', 'Premi extra per calma sociale', 'Evitare sovrastimolazione'],
   ARRAY['Aiutanti collaborativi', 'Spazi controllati']),
  (13, 'Consolidamento Avanzato', 'Rinforzo finale delle competenze apprese', 25,
   ARRAY['Combinare tutti gli stimoli precedenti', 'Test in situazioni semi-reali', 'Ridurre gradualmente supporto attivo', 'Preparare piano mantenimento'],
   ARRAY['Tutti i materiali precedenti']),
  (14, 'Piano Mantenimento Lungo Termine', 'Strategie per mantenere progressi', 20,
   ARRAY['Creare routine di mantenimento settimanale', 'Identificare segnali di ricaduta', 'Piano di intervento rapido', 'Celebrazione completamento programma'],
   ARRAY['Calendario mantenimento', 'Protocollo emergenza'])
) AS exercises(day_num, title, description, duration, instructions, materials)
WHERE p.title = 'Superare Fobie e Paure Specifiche';