-- Crea tutti gli esercizi per il protocollo "Socializzazione Progressiva" (14 giorni, 42 esercizi)
DO $$
DECLARE
    protocol_uuid UUID;
BEGIN
    -- Trova l'ID del protocollo per la socializzazione
    SELECT id INTO protocol_uuid 
    FROM ai_training_protocols 
    WHERE category = 'socializzazione'
    LIMIT 1;
    
    IF protocol_uuid IS NOT NULL THEN
        INSERT INTO ai_training_exercises (protocol_id, day_number, title, description, instructions, exercise_type, duration_minutes, materials) VALUES
        -- GIORNO 1
        (protocol_uuid, 1, 'Valutazione Sociale Iniziale', 'Osservazione baseline del comportamento sociale attuale', ARRAY['Osserva come il pet reagisce a suoni di altri animali', 'Nota le reazioni a voci umane sconosciute', 'Registra livello di ansia/curiosità verso l''esterno', 'Testa la reazione a stimoli sociali dalla finestra', 'Documenta tutto nel diario sociale'], 'social', 15, ARRAY['Diario sociale', 'Registratore audio/video']),
        (protocol_uuid, 1, 'Rinforzo Positivo Base', 'Stabilire fondamenta per associazioni positive', ARRAY['Ogni volta che senti rumori sociali (persone, animali), dai un treat', 'Il pet deve associare suoni sociali a cose positive', 'Non forzare l''interazione, solo rinforza la calma', 'Usa treats di alto valore che riservi solo per questo', 'Ripeti per almeno 20 situazioni'], 'social', 20, ARRAY['Treats premium', 'Cronometro']),
        (protocol_uuid, 1, 'Desensibilizzazione Audio Leggera', 'Introduzione graduale a suoni sociali controllati', ARRAY['Riproduci suoni di cani che abbaiano a volume MOLTO basso', 'Se il pet resta calmo, premia immediatamente', 'Se mostra stress, riduci ulteriormente il volume', 'Durata: 10 minuti massimo', 'Termina sempre con successo e premio'], 'social', 10, ARRAY['Speaker/telefono', 'Audio cani/gatti', 'Treats']),

        -- GIORNO 2
        (protocol_uuid, 2, 'Comando "Guarda Me" Perfezionato', 'Aumentare l''attenzione e controllo in presenza di distrazioni', ARRAY['Insegna/rafforza il comando "guardami" o "occhi"', 'Inizia senza distrazioni, premia il contatto visivo', 'Aggiungi gradualmente distrazioni leggere', 'Il pet deve imparare a focalizzarsi su di te', 'Sessioni brevi ma frequenti durante il giorno'], 'social', 15, ARRAY['Treats piccoli e frequenti', 'Spazio tranquillo']),
        (protocol_uuid, 2, 'Esposizione Visiva Controllata', 'Abituare alla vista di altri esseri viventi a distanza', ARRAY['Posiziona il pet vicino a una finestra con vista su strada/giardino', 'Quando vede persone/animali lontani, premialo se resta calmo', 'Mantieni sempre distanza di sicurezza', 'Se si agita, distrailo con comandi che conosce', 'Incrementa gradualmente il tempo di osservazione'], 'social', 25, ARRAY['Finestra con vista', 'Treats', 'Toys di distrazione']),
        (protocol_uuid, 2, 'Gioco Interattivo Intensificato', 'Aumentare fiducia attraverso gioco strutturato', ARRAY['Gioca intensivamente con il pet per 15 minuti', 'Usa giochi che aumentano la sua fiducia', 'Varia i giochi: tira e molla, nascondino, puzzle', 'L''obiettivo è renderlo sicuro e felice', 'Termina con molte lodi e coccole'], 'social', 15, ARRAY['Variety di toys', 'Spazio per giocare']),

        -- GIORNO 3
        (protocol_uuid, 3, 'Prima Uscita di Osservazione', 'Valutazione del comportamento in ambiente esterno controllato', ARRAY['Porta il pet in un luogo tranquillo all''aperto', 'Scegli un momento con poche persone/animali', 'Osserva le sue reazioni senza forzare interazioni', 'Mantieni sempre il controllo con guinzaglio/trasportino', 'Durata breve, focus sulla calma e osservazione'], 'social', 20, ARRAY['Guinzaglio/pettorina', 'Treats calmanti', 'Area tranquilla']),
        (protocol_uuid, 3, 'Comando "Posto" in Situazioni Sociali', 'Insegnare autocontrollo in presenza di stimoli sociali', ARRAY['Pratica il comando "posto" o "seduto" con distrazioni minime', 'Aggiungi gradualmente suoni sociali di fondo', 'Il pet deve mantenere la posizione nonostante le distrazioni', 'Premia immediatamente ogni successo', 'Aumenta durata gradualmente: da 5 a 30 secondi'], 'social', 20, ARRAY['Treats', 'Audio di fondo leggero']),
        (protocol_uuid, 3, 'Socializzazione Indiretta con Barriera', 'Interazione sicura attraverso recinzioni/vetri', ARRAY['Trova un''area con recinzione dove può vedere altri animali', 'Mantieni distanza sufficiente per evitare stress', 'Premia ogni comportamento calmo verso l''altro animale', 'Se si agita, allontanati gradualmente', 'Focus su associazioni positive, non su interazione diretta'], 'social', 30, ARRAY['Luogo con recinzione sicura', 'Treats premium']),

        -- GIORNO 4
        (protocol_uuid, 4, 'Desensibilizzazione a Persone Lontane', 'Abituare alla presenza umana a distanza di sicurezza', ARRAY['Porta il pet in un luogo dove può vedere persone da lontano', 'Inizia con distanza molto ampia (50+ metri)', 'Ogni volta che vede una persona e resta calmo, premia', 'Se mostra interesse positivo (coda, orecchie dritte), super-premio', 'Non permettere avvicinamenti non controllati'], 'social', 25, ARRAY['Area aperta', 'Treats di alto valore', 'Guinzaglio lungo']),
        (protocol_uuid, 4, 'Comando di Richiamo Potenziato', 'Rafforzare il controllo in situazioni sociali', ARRAY['Pratica il richiamo "vieni" con distrazioni crescenti', 'Inizia in casa, poi in giardino, poi in area più stimolante', 'Il pet deve rispondere immediatamente anche con distrazioni', 'Usa sempre guinzaglio lungo per sicurezza', 'Premia abbondantemente ogni richiamo riuscito'], 'social', 20, ARRAY['Guinzaglio lungo (5-10m)', 'Treats irresistibili']),
        (protocol_uuid, 4, 'Simulazione Incontri Controllati', 'Preparazione per futuri incontri reali', ARRAY['Simula incontri usando pupazzi, peluche o foto', 'Presenta "l''amico" gradualmente', 'Premia ogni reazione positiva o neutrale', 'Se il pet vuole giocare con il pupazzo, permetti ma controlla', 'Questo insegna che "nuovi amici" sono cose buone'], 'social', 15, ARRAY['Pupazzi/peluche di animali', 'Treats', 'Foto di animali']),

        -- GIORNO 5
        (protocol_uuid, 5, 'Prima Interazione Umana Supervisionata', 'Incontro controllato con persona calma e paziente', ARRAY['Organizza incontro con persona che conosce i protocolli', 'La persona deve ignorare completamente il pet inizialmente', 'Permetti al pet di avvicinarsi ai suoi tempi', 'La persona può offrire treats solo se il pet è interessato', 'Durata breve: 10-15 minuti massimo'], 'social', 30, ARRAY['Persona collaborativa', 'Treats da far offrire', 'Ambiente familiare']),
        (protocol_uuid, 5, 'Rinforzo Comportamenti Sociali Positivi', 'Consolidare segnali di apertura sociale', ARRAY['Osserva e premia ogni segnale sociale positivo', 'Coda che scodinzola, orecchie rilassate, avvicinamento volontario', 'Usa marcatore verbale ("bravo!") + treat immediato', 'Ignora comportamenti ansiosi, premia solo i positivi', 'Crea "banca dati" di comportamenti da rinforzare'], 'social', 20, ARRAY['Lista comportamenti positivi', 'Treats immediati']),
        (protocol_uuid, 5, 'Passeggiata di Osservazione Sociale', 'Esposizione controllata a ambiente sociale più ricco', ARRAY['Scegli percorso con moderata attività sociale', 'Mantieni sempre controllo e distanze di sicurezza', 'Fermati spesso per premiare comportamenti calmi', 'Se incontra altri, permetti osservazione ma non interazione', 'Focus: abituare, non socializzare direttamente'], 'social', 25, ARRAY['Percorso pianificato', 'Treats frequenti', 'Guinzaglio sicuro']),

        -- GIORNO 6
        (protocol_uuid, 6, 'Controllo Impulsi in Situazioni Sociali', 'Autocontrollo quando vede stimoli interessanti', ARRAY['Pratica "aspetta" quando vede persone/animali', 'Il pet deve imparare che può guardare ma non tirare/correre', 'Usa comando "fermo" o "easy" quando si eccita', 'Premia solo quando è calmo e controllato', 'Gradualmente riduci la distanza dagli stimoli'], 'social', 30, ARRAY['Stimoli sociali controllati', 'Treats per autocontrollo']),
        (protocol_uuid, 6, 'Socializzazione con Oggetti Sociali', 'Abituare a oggetti associati con attività sociali', ARRAY['Introduci oggetti: guinzagli di altri animali, ciotole multiple, giochi condivisi', 'Permetti esplorazione e annusata di questi oggetti', 'Premia curiosità e comportamenti rilassati', 'Questi oggetti porteranno odori di altri animali', 'Gradualmente diventeranno "normali" e non stressanti'], 'social', 20, ARRAY['Oggetti con odori sociali', 'Treats per esplorazione']),
        (protocol_uuid, 6, 'Test di Tolleranza Spaziale', 'Verificare comfort in spazi condivisi', ARRAY['Porta il pet in area dove altri animali sono stati di recente', 'Lascialo esplorare e annusare liberamente', 'Osserva linguaggio del corpo: deve essere rilassato', 'Premia esplorazione calma e interesse positivo', 'Se mostra stress, allontanati e riprova domani'], 'social', 25, ARRAY['Area con tracce odorose', 'Osservazione attenta']),

        -- GIORNO 7
        (protocol_uuid, 7, 'Incontro a Distanza Programmato', 'Prima vera socializzazione a distanza sicura', ARRAY['Organizza incontro con animale calmo a distanza di 10+ metri', 'Entrambi gli animali devono essere al guinzaglio con proprietari esperti', 'Permetti solo osservazione reciproca, nessun avvicinamento', 'Premia ogni secondo di comportamento calmo', 'Se entrambi sono rilassati, riduci distanza di 1-2 metri'], 'social', 40, ARRAY['Animale partner calmo', 'Spazio ampio', 'Coordinamento con altro proprietario']),
        (protocol_uuid, 7, 'Consolidamento Comandi Sociali', 'Ripasso di tutti i comandi in contesto sociale', ARRAY['Pratica tutti i comandi imparati con distrazioni sociali', 'Seduto, resta, vieni, guardami - tutti con stimoli sociali presenti', 'Il pet deve dimostrare controllo completo', 'Questo è il test di preparazione per interazioni più strette', 'Premia performance eccellenti con sessione di gioco'], 'social', 20, ARRAY['Distrazioni sociali varie', 'Super-treats per performance']),
        (protocol_uuid, 7, 'Valutazione Progressi Settimanali', 'Analisi completa dei miglioramenti della prima settimana', ARRAY['Confronta comportamento di oggi con il Giorno 1', 'Documenta tutti i progressi osservati', 'Identifica aree che necessitano più lavoro', 'Pianifica obiettivi per la seconda settimana', 'Celebra ogni progresso, anche piccolo'], 'social', 15, ARRAY['Diario sociale iniziale', 'Piano per settimana 2']),

        -- GIORNO 8
        (protocol_uuid, 8, 'Introduzione Giochi Sociali Simulati', 'Preparazione per giochi con altri animali', ARRAY['Introduci giochi che simulano interazione: tira e molla con due persone', 'Il pet impara che i giochi possono coinvolgere più partecipanti', 'Premia condivisione e gioco non possessivo', 'Se diventa possessivo del gioco, pausa e riprova', 'Obiettivo: insegnare che condividere è divertente'], 'social', 25, ARRAY['Giochi condivisibili', 'Due persone per giocare']),
        (protocol_uuid, 8, 'Desensibilizzazione Avvicinamento Laterale', 'Abituare ad approcci non frontali', ARRAY['Pratica avvicinamenti da lato invece che frontali', 'Gli approcci laterali sono meno minacciosi per gli animali', 'Fai camminare persone/animali parallel al pet, non verso', 'Premia calma durante questi approcci laterali', 'Gradualmente riduci la distanza laterale'], 'social', 20, ARRAY['Spazio per movimenti laterali', 'Assistenti per simulazioni']),
        (protocol_uuid, 8, 'Comando "Saluta" Controllato', 'Insegnare modalità appropriate di saluto', ARRAY['Insegna comando specifico per iniziare interazioni sociali', 'Il pet può avvicinarsi solo quando autorizzato', 'Pratica con persone che sanno come comportarsi', 'Se il pet saluta troppo energicamente, richiamalo', 'Obiettivo: saluti educati e controllati'], 'social', 15, ARRAY['Persone collaborative per saluti', 'Treats per saluti appropriati']),

        -- GIORNO 9
        (protocol_uuid, 9, 'Prima Interazione Diretta Breve', 'Contatto diretto supervisionato con animale calmo', ARRAY['Organizza incontro diretto con animale molto socializzato', 'Durata massima: 5 minuti di interazione diretta', 'Entrambi al guinzaglio, proprietari esperti presenti', 'Interrompi immediatamente se c''è tensione', 'Premia ogni secondo di interazione positiva'], 'social', 35, ARRAY['Partner animale esperto', 'Due guinzagli', 'Spazio controllato']),
        (protocol_uuid, 9, 'Gestione Eccitazione Sociale', 'Controllo quando il pet diventa troppo eccitato', ARRAY['Insegna comando "calmo" o "rilassa" per gestire ipereccitazione', 'Pratica quando il pet è moderatamente eccitato', 'Se si eccita troppo durante interazioni sociali, usa il comando', 'Premia immediatamente quando si calma', 'Questo comando sarà cruciale per interazioni future'], 'social', 20, ARRAY['Situazioni di moderata eccitazione', 'Treats calmanti']),
        (protocol_uuid, 9, 'Socializzazione Olfattiva Avanzata', 'Esposizione a odori sociali più intensi', ARRAY['Porta il pet in aree dove molti animali sono stati recentemente', 'Parchi per cani (fuori dalla recinzione), negozi per animali', 'Lascialo annusare e processare tutti gli odori sociali', 'Questo è "socializzazione digitale" - impara senza interagire', 'Premia curiosità e rilassamento durante l''esplorazione'], 'social', 30, ARRAY['Aree ricche di odori sociali', 'Tempo per elaborazione olfattiva']),

        -- GIORNO 10
        (protocol_uuid, 10, 'Test Avvicinamento Graduale', 'Verifica capacità di gestire avvicinamenti progressivi', ARRAY['Inizia con distanza sicura da altro animale (5+ metri)', 'Avvicinati di un passo ogni 30 secondi se entrambi sono calmi', 'Fermati immediatamente se c''è tensione', 'L''obiettivo è arrivare a 2 metri di distanza', 'Premia ogni passo di avvicinamento riuscito'], 'social', 40, ARRAY['Animale partner paziente', 'Spazio misurato per avvicinamento']),
        (protocol_uuid, 10, 'Comando "Lascia" Sociale', 'Controllo quando il pet si fissa su altri animali', ARRAY['Insegna "lascia" o "basta" quando il pet fissa intensamente', 'Pratica con stimoli sociali a distanza sicura', 'Il pet deve imparare a distogliere l''attenzione su comando', 'Premia immediatamente quando distoglie lo sguardo', 'Questo previene escalation in situazioni tese'], 'social', 15, ARRAY['Stimoli sociali per pratica', 'Treats immediati per distrazione']),
        (protocol_uuid, 10, 'Gioco Parallelo Introducato', 'Attività simultanee ma indipendenti con altri animali', ARRAY['Organizza attività dove due animali giocano vicini ma non insieme', 'Esempio: entrambi seguono percorsi paralleli con treats', 'Nessuna competizione o interazione diretta', 'L''obiettivo è abituarsi alla presenza durante attività positive', 'Mantieni sempre controllo di entrambi gli animali'], 'social', 25, ARRAY['Percorsi paralleli', 'Treats per entrambi', 'Partner animale']),

        -- GIORNO 11
        (protocol_uuid, 11, 'Socializzazione in Movimento', 'Interazioni sociali durante passeggiate', ARRAY['Organizza passeggiata parallela con altro animale e proprietario', 'Mantieni distanza di 3-5 metri durante la camminata', 'Se entrambi sono rilassati, riduci gradualmente la distanza', 'Questo simula incontri naturali durante passeggiate', 'Termina sempre con successo prima che ci sia stress'], 'social', 30, ARRAY['Percorso di passeggiata', 'Partner per camminata parallela']),
        (protocol_uuid, 11, 'Controllo Territorialità Leggera', 'Gestione possessività di spazi e oggetti', ARRAY['Testa reazione quando altri si avvicinano a "suoi" oggetti', 'Inizia con oggetti di basso valore', 'Se mostra possessività, usa comando "lascia" e premio', 'Gradualmente testa con oggetti di valore crescente', 'L''obiettivo è ridurre territorialità eccessiva'], 'social', 20, ARRAY['Oggetti di valore variabile', 'Partner per testare possessività']),
        (protocol_uuid, 11, 'Comunicazione Corporea Positiva', 'Rinforzo segnali corporei amichevoli', ARRAY['Osserva e premia linguaggio corporeo positivo', 'Coda rilassata, orecchie normali, postura sciolta', 'Fotografa o filma questi momenti per riferimento', 'Usa questi momenti come "modello" di comportamento ideale', 'Premia immediatamente ogni segnale amichevole'], 'social', 15, ARRAY['Camera per documentare', 'Treats per segnali positivi']),

        -- GIORNO 12
        (protocol_uuid, 12, 'Interazione Sociale Estesa', 'Periodo più lungo di socializzazione diretta', ARRAY['Organizza sessione di 10-15 minuti con animale compatibile', 'Mantieni supervisione costante ma permetti più libertà', 'Intervieni solo se necessario per sicurezza', 'Permetti sviluppo naturale di dinamiche sociali positive', 'Documenta tutti i comportamenti per analisi'], 'social', 45, ARRAY['Partner animale molto compatibile', 'Spazio sicuro esteso']),
        (protocol_uuid, 12, 'Gestione Conflitti Minori', 'Intervento in piccole tensioni sociali', ARRAY['Se si verificano piccole tensioni, pratica de-escalation', 'Usa distrazioni positive invece di punizioni', 'Richiama entrambi gli animali e ricompensa il disimpegno', 'Insegna che evitare conflitti è premiato', 'Non punire mai tensioni naturali, solo reindirizza'], 'social', 20, ARRAY['Tecniche di distrazione', 'Treats per disimpegno']),
        (protocol_uuid, 12, 'Condivisione Spazio Controllata', 'Utilizzo pacifico dello stesso ambiente', ARRAY['Permetti al pet di condividere spazio con altri animali', 'Inizia con spazi ampi, gradualmente riduci', 'Premia ogni momento di coesistenza pacifica', 'Se c''è tensione, aumenta lo spazio disponibile', 'L''obiettivo è comfort in spazi condivisi'], 'social', 25, ARRAY['Spazio modulabile', 'Più animali collaborativi']),

        -- GIORNO 13
        (protocol_uuid, 13, 'Test Socializzazione Multipla', 'Gestione presenza di più animali simultaneamente', ARRAY['Introduce gradualmente più animali nell''ambiente', 'Inizia con animali molto socializzati e calmi', 'Mantieni il controllo sempre, non lasciare mai senza supervisione', 'Osserva come gestisce dinamiche di gruppo', 'Premia comportamenti appropriati in contesto di gruppo'], 'social', 50, ARRAY['Gruppo di animali esperti', 'Spazio ampio per gruppo']),
        (protocol_uuid, 13, 'Consolidamento Tutti i Comandi', 'Test finale di controllo in ambiente sociale complesso', ARRAY['Pratica tutti i comandi appresi in situazione sociale ricca', 'Il pet deve rispondere ai comandi anche con molte distrazioni', 'Testa: seduto, resta, vieni, guardami, calmo, lascia', 'Questo dimostra controllo completo necessario per socializzazione', 'Performance perfetta = celebrazione speciale'], 'social', 20, ARRAY['Ambiente con molte distrazioni sociali', 'Lista comandi da testare']),
        (protocol_uuid, 13, 'Preparazione Indipendenza Sociale', 'Riduzione graduale della supervisione diretta', ARRAY['Permetti più autonomia nelle interazioni sociali', 'Riduci interventi diretti, osserva più da lontano', 'Intervieni solo per sicurezza, non per ogni piccola cosa', 'Il pet deve imparare a gestire autonomamente situazioni sociali', 'Documenta livello di indipendenza raggiunto'], 'social', 30, ARRAY['Osservazione a distanza', 'Interventi solo per sicurezza']),

        -- GIORNO 14
        (protocol_uuid, 14, 'Valutazione Finale Completa', 'Test conclusivo di tutte le competenze sociali', ARRAY['Organizza test completo in ambiente sociale reale', 'Il pet deve dimostrare tutte le competenze apprese', 'Incontri, separazioni, giochi, condivisione spazio', 'Documenta ogni comportamento per valutazione finale', 'Questo determina il livello di socializzazione raggiunto'], 'social', 60, ARRAY['Ambiente sociale reale', 'Documentazione completa']),
        (protocol_uuid, 14, 'Pianificazione Mantenimento', 'Strategia per conservare progressi ottenuti', ARRAY['Analizza tutti i progressi fatti in 14 giorni', 'Identifica punti di forza e aree che necessitano rinforzo', 'Crea piano di mantenimento per evitare regressioni', 'Stabilisci frequenza di esposizioni sociali necessarie', 'Prepara protocollo per nuove situazioni sociali'], 'social', 20, ARRAY['Analisi completa progressi', 'Piano mantenimento scritto']),
        (protocol_uuid, 14, 'Celebrazione e Graduazione', 'Riconoscimento successi e proiezione futura', ARRAY['Celebra tutti i progressi fatti con attività speciale', 'Riconosci sforzi sia del pet che del proprietario', 'Documenta il "prima e dopo" del percorso', 'Pianifica prossimi obiettivi sociali avanzati', 'Il pet è ora pronto per socializzazioni indipendenti!'], 'social', 30, ARRAY['Attività celebrativa speciale', 'Documentazione finale']);
    END IF;
END $$;