-- MEGA TRADUZIONE PARTE 2: RESTO DEI TITOLI
-- Continua con il resto dei titoli degli esercizi

UPDATE ai_training_exercises SET title = 'Intensive Eye Contact' WHERE title = 'Contatto Visivo Intensivo';
UPDATE ai_training_exercises SET title = 'Social Excitement Control' WHERE title = 'Controllo Eccitazione Sociale';
UPDATE ai_training_exercises SET title = 'Door Impulse Control' WHERE title = 'Controllo Impulsi Porta';
UPDATE ai_training_exercises SET title = 'Impulse Control Near Resources' WHERE title = 'Controllo Impulsi Vicino a Risorse';
UPDATE ai_training_exercises SET title = 'Maximum Distance Counter-Conditioning' WHERE title = 'Counter-Conditioning Distanza Massima';
UPDATE ai_training_exercises SET title = 'Counter-Conditioning Level 1' WHERE title = 'Counter-Conditioning Livello 1';
UPDATE ai_training_exercises SET title = 'Personal Chewing Corner Creation' WHERE title = 'Creazione Angolo Masticazione Personale';
UPDATE ai_training_exercises SET title = 'Safe Space Creation' WHERE title = 'Creazione Safe Space';
UPDATE ai_training_exercises SET title = 'Personalized Safe Space Creation' WHERE title = 'Creazione Safe Space Personalizzato';
UPDATE ai_training_exercises SET title = 'Advanced Cue Desensitization' WHERE title = 'Desensibilizzazione Avanzata Cue';
UPDATE ai_training_exercises SET title = 'Gradual Approach Desensitization' WHERE title = 'Desensibilizzazione Avvicinamento Graduale';
UPDATE ai_training_exercises SET title = 'Hands Near Food Desensitization' WHERE title = 'Desensibilizzazione Mani Vicino al Cibo';
UPDATE ai_training_exercises SET title = 'Human Presence Desensitization' WHERE title = 'Desensibilizzazione Presenza Umana';
UPDATE ai_training_exercises SET title = 'Visual Distance Desensitization' WHERE title = 'Desensibilizzazione Visiva Distanza';
UPDATE ai_training_exercises SET title = 'Advanced Discrimination' WHERE title = 'Discriminazione Avanzata';
UPDATE ai_training_exercises SET title = 'Progressive Exposure Duration' WHERE title = 'Durata Esposizione Progressiva';
UPDATE ai_training_exercises SET title = 'Food Anxiety Elimination' WHERE title = 'Eliminazione Ansia Alimentare';
UPDATE ai_training_exercises SET title = 'Food Competition Elimination' WHERE title = 'Eliminazione Competizione Alimentare';
UPDATE ai_training_exercises SET title = 'Wait Your Turn Exercise' WHERE title = 'Esercizio "Aspetta il Tuo Turno"';
UPDATE ai_training_exercises SET title = '2-Minute Extension' WHERE title = 'Estensione a 2 Minuti';
UPDATE ai_training_exercises SET title = 'Focus in Movement' WHERE title = 'Focus in Movimento';
UPDATE ai_training_exercises SET title = 'Controlled Free Choice Feeding' WHERE title = 'Free Choice Feeding Controllato';
UPDATE ai_training_exercises SET title = 'Cooperative Tug of War Game' WHERE title = 'Gioco Cooperativo "Tira e Molla"';
UPDATE ai_training_exercises SET title = 'Complex Cooperative Game' WHERE title = 'Gioco Cooperativo Complesso';
UPDATE ai_training_exercises SET title = 'Extended Interactive Play' WHERE title = 'Gioco Interattivo Prolungato';
UPDATE ai_training_exercises SET title = 'Parallel Play with Other Animals' WHERE title = 'Gioco Parallelo con Altri Animali';
UPDATE ai_training_exercises SET title = 'Pause and Go Game' WHERE title = 'Gioco Pausa e Vai';
UPDATE ai_training_exercises SET title = 'Sudden Stop Game' WHERE title = 'Gioco Stop Improvviso';
UPDATE ai_training_exercises SET title = 'Structured Anti-Boredom Play' WHERE title = 'Gioco Strutturato Anti-Noia';
UPDATE ai_training_exercises SET title = 'Supervised Group Activity' WHERE title = 'Group Activity Supervisionata';
UPDATE ai_training_exercises SET title = 'Controlled Hand Feeding' WHERE title = 'Hand Feeding Controllato';
UPDATE ai_training_exercises SET title = 'Primary Trigger Identification' WHERE title = 'Identificazione Trigger Primario';
UPDATE ai_training_exercises SET title = 'Graduated Impulse Control' WHERE title = 'Impulse Control Graduato';
UPDATE ai_training_exercises SET title = 'Alternative Behaviors Integration' WHERE title = 'Integration Alternative Behaviors';
UPDATE ai_training_exercises SET title = 'Social Integration Test' WHERE title = 'Integration Test Sociale';
UPDATE ai_training_exercises SET title = 'Comfort Object Introduction' WHERE title = 'Introduzione Comfort Object';
UPDATE ai_training_exercises SET title = 'Gradual Second Animal Introduction' WHERE title = 'Introduzione Graduale Secondo Animale';
UPDATE ai_training_exercises SET title = 'Human Presence Introduction at Distance' WHERE title = 'Introduzione Presenza Umana a Distanza';
UPDATE ai_training_exercises SET title = 'Voice Recording Introduction' WHERE title = 'Introduzione Registrazione Voce';
UPDATE ai_training_exercises SET title = 'Slow Feeding Introduction' WHERE title = 'Introduzione Slow Feeding';
UPDATE ai_training_exercises SET title = 'Snuffle Mat Introduction' WHERE title = 'Introduzione Tappetino Snuffle';
UPDATE ai_training_exercises SET title = 'Leadership and Initiative' WHERE title = 'Leadership e Iniziativa';
UPDATE ai_training_exercises SET title = 'Evening Anti-Stress Massage' WHERE title = 'Massaggio Serale Anti-Stress';
UPDATE ai_training_exercises SET title = 'Guided Pet Meditation' WHERE title = 'Meditazione Guidata Pet';
UPDATE ai_training_exercises SET title = 'Controlled Meet-and-Greet' WHERE title = 'Meet-and-Greet Controllato';
UPDATE ai_training_exercises SET title = 'Intensive Mental Stimulation' WHERE title = 'Mental Stimulation Intensiva';
UPDATE ai_training_exercises SET title = 'Audio Micro-Exposure' WHERE title = 'Micro-Esposizione Audio';
UPDATE ai_training_exercises SET title = '30-Second Micro-Exits' WHERE title = 'Micro-Uscite di 30 Secondi';
UPDATE ai_training_exercises SET title = 'Return Neutralization' WHERE title = 'Neutralizzazione Rientro';
UPDATE ai_training_exercises SET title = 'Introductory Parallel Walking' WHERE title = 'Parallel Walking Introduttivo';
UPDATE ai_training_exercises SET title = 'Delayed Reward Patience' WHERE title = 'Pazienza Ricompensa Ritardata';
UPDATE ai_training_exercises SET title = 'Timed Obstacle Course' WHERE title = 'Percorso Ostacoli Temporizzato';
UPDATE ai_training_exercises SET title = 'Maintenance Planning' WHERE title = 'Pianificazione Mantenimento';
UPDATE ai_training_exercises SET title = 'Personalized Maintenance Plan' WHERE title = 'Piano Mantenimento Personalizzato';
UPDATE ai_training_exercises SET title = 'Positive Association with Strangers' WHERE title = 'Positive Association con Estranei';
UPDATE ai_training_exercises SET title = 'Calm Presence During Meals' WHERE title = 'Presenza Calma Durante i Pasti';
UPDATE ai_training_exercises SET title = 'Stranger Presence During Feeding' WHERE title = 'Presenza di Estranei Durante l''Alimentazione';
UPDATE ai_training_exercises SET title = 'First NO Training and Redirection' WHERE title = 'Primo Training "NO" e Redirezione';