-- MEGA TRADUZIONE PARTE 1: TITOLI DEGLI ESERCIZI (CORRETTA)
-- Aggiorna TUTTI i titoli degli esercizi

UPDATE ai_training_exercises SET title = 'Morning Positive Routine' WHERE title = '🌅 Routine Positiva Nuova';
UPDATE ai_training_exercises SET title = 'Stimulating Colors Game' WHERE title = '🌈 Gioco Colori Stimolanti';
UPDATE ai_training_exercises SET title = 'Simple Wavy Path' WHERE title = '🌊 Percorso Ondulato Semplice';
UPDATE ai_training_exercises SET title = 'Gentle Olfactory Awakening' WHERE title = '🌸 Risveglio Olfattivo Delicato';
UPDATE ai_training_exercises SET title = 'Guided Indoor Exploration' WHERE title = '🌿 Esplorazione Guidata Indoor';
UPDATE ai_training_exercises SET title = 'Motivating Surprise Box' WHERE title = '🎁 Scatola Sorpresa Motivante';
UPDATE ai_training_exercises SET title = 'Progress Celebration' WHERE title = '🎊 Celebrazione Progressi';
UPDATE ai_training_exercises SET title = 'Free Creative Activity' WHERE title = '🎨 Attività Creativa Libera';
UPDATE ai_training_exercises SET title = 'Motivating Interactive Game' WHERE title = '🎪 Gioco Interattivo Motivante';
UPDATE ai_training_exercises SET title = 'Easy Motivating Tricks' WHERE title = '🎪 Trick Facili Motivanti';
UPDATE ai_training_exercises SET title = 'Basic Target Training' WHERE title = '🎯 Target Training Base';
UPDATE ai_training_exercises SET title = 'Multiple Choice Game' WHERE title = '🎲 Gioco delle Scelte Multiple';
UPDATE ai_training_exercises SET title = 'Gentle Sound Awakening' WHERE title = '🎵 Risveglio Sonoro Dolce';
UPDATE ai_training_exercises SET title = 'Gentle Ball Game' WHERE title = '🎾 Gioco Palla Dolce';
UPDATE ai_training_exercises SET title = 'Controlled Gentle Socialization' WHERE title = '👥 Socializzazione Dolce Controllata';
UPDATE ai_training_exercises SET title = 'Motivating Relaxing Massage' WHERE title = '💆 Massaggio Rilassante Motivante';
UPDATE ai_training_exercises SET title = 'Positive Future Planning' WHERE title = '💫 Pianificazione Futuro Positivo';
UPDATE ai_training_exercises SET title = 'Simple Motivating Sequences' WHERE title = '🔄 Sequenze Semplici Motivanti';
UPDATE ai_training_exercises SET title = 'Guided Olfactory Search' WHERE title = '🔍 Ricerca Olfattiva Guidata';
UPDATE ai_training_exercises SET title = 'Simple Hidden Treasure' WHERE title = '🤲 Tesoro Nascosto Semplice';
UPDATE ai_training_exercises SET title = 'Easy Food Puzzle' WHERE title = '🧩 Puzzle Alimentare Facile';
UPDATE ai_training_exercises SET title = 'Soft Texture Exploration' WHERE title = '🪶 Esplorazione Texture Morbide';
UPDATE ai_training_exercises SET title = 'Motivated Autonomy Test' WHERE title = '🚀 Test Autonomia Motivata';
UPDATE ai_training_exercises SET title = 'Awakening Steps' WHERE title = '🚶 Passi di Risveglio';
UPDATE ai_training_exercises SET title = 'Multi-Pet Controlled Feeding' WHERE title = 'Alimentazione Controllata Multi-Pet';
UPDATE ai_training_exercises SET title = 'Timed Fractioned Feeding' WHERE title = 'Alimentazione Frazionata Temporizzata';
UPDATE ai_training_exercises SET title = 'Alternative Response Training' WHERE title = 'Alternative Response Training';
UPDATE ai_training_exercises SET title = 'Positive Anticipation' WHERE title = 'Anticipazione Positiva';
UPDATE ai_training_exercises SET title = 'Complex Positive Associations' WHERE title = 'Associazioni Positive Complesse';
UPDATE ai_training_exercises SET title = 'Shared Attention with Owner' WHERE title = 'Attenzione Condivisa con il Proprietario';
UPDATE ai_training_exercises SET title = 'Home Audit and Risk Zone Identification' WHERE title = 'Audit Casa e Identificazione Zone Rischio';
UPDATE ai_training_exercises SET title = 'Self-Control with Frustration' WHERE title = 'Autocontrollo con Frustrazione';
UPDATE ai_training_exercises SET title = 'Self-Control During Exposure' WHERE title = 'Autocontrollo Durante Esposizione';
UPDATE ai_training_exercises SET title = 'Multi-Distraction Self-Control' WHERE title = 'Autocontrollo Multi-Distrazione';
UPDATE ai_training_exercises SET title = 'Real Situations Self-Control' WHERE title = 'Autocontrollo Situazioni Reali';
UPDATE ai_training_exercises SET title = 'Gradual Approach to Resources' WHERE title = 'Avvicinamento Graduale alle Risorse';
UPDATE ai_training_exercises SET title = 'Behavioral Baseline' WHERE title = 'Baseline Comportamentale';
UPDATE ai_training_exercises SET title = 'Multi-Level Treasure Hunt' WHERE title = 'Caccia al Tesoro Multi-Livello';
UPDATE ai_training_exercises SET title = 'Speed Control Walking' WHERE title = 'Camminata Controllo Velocità';
UPDATE ai_training_exercises SET title = 'Celebration and Success Consolidation' WHERE title = 'Celebration e Consolidamento Successi';
UPDATE ai_training_exercises SET title = 'Celebration and Graduation' WHERE title = 'Celebrazione e Graduation';
UPDATE ai_training_exercises SET title = 'Celebration and Final Reinforcement' WHERE title = 'Celebrazione e Rinforzo Finale';
UPDATE ai_training_exercises SET title = 'Advanced Impulse Challenge' WHERE title = 'Challenge Impulsi Avanzato';
UPDATE ai_training_exercises SET title = 'Basic Home Agility Circuit' WHERE title = 'Circuito Agility Casa Base';
UPDATE ai_training_exercises SET title = 'Advanced Drop It Command' WHERE title = 'Comando "Drop It" Avanzato';
UPDATE ai_training_exercises SET title = 'Basic LEAVE Command' WHERE title = 'Comando "LASCIA" Base';
UPDATE ai_training_exercises SET title = 'Everyone to Their Place Command' WHERE title = 'Comando "Ognuno al Suo Posto"';
UPDATE ai_training_exercises SET title = 'Progressive Wait Command' WHERE title = 'Comando Aspetta Progressivo';
UPDATE ai_training_exercises SET title = 'Graduated Audio-Visual Combination' WHERE title = 'Combinazione Audio-Visiva Graduata';
UPDATE ai_training_exercises SET title = 'Multiple Bowl Sharing' WHERE title = 'Condivisione Ciotole Multiple';
UPDATE ai_training_exercises SET title = 'Guided Sharing with Owner' WHERE title = 'Condivisione Guidata con Proprietario';
UPDATE ai_training_exercises SET title = 'Space Sharing with Other Animals' WHERE title = 'Condivisione Spazio con Altri Animali';
UPDATE ai_training_exercises SET title = 'Calm Marker Conditioning' WHERE title = 'Condizionamento Marker di Calma';
UPDATE ai_training_exercises SET title = 'Emotional Consolidation' WHERE title = 'Consolidamento Emotivo';
UPDATE ai_training_exercises SET title = 'Final Consolidation and Evaluation' WHERE title = 'Consolidamento Finale e Valutazione';
UPDATE ai_training_exercises SET title = 'Learned Strategies Consolidation' WHERE title = 'Consolidamento Strategie Apprese';