// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unwxkufzauulzhmjxxqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVud3hrdWZ6YXV1bHpobWp4eHFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDcwMTIsImV4cCI6MjA2NzU4MzAxMn0.QfjmWCFEIaHzeYy0Z1gROZQchzqcCCo9In4ayqR3cXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});